### ISSUE TITLE
Add `includeReceiptEmailInRequests` to settings

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-stripe#1]
For 1.2 commerce gateway compatibility add a `includeReceiptEmailInRequests` (bool) setting to the gateway.

When building the request, depending on the setting, include or don't include the `receipt_email` data in the stripe request.

(just noting this here to be done after gateway refactor)

**Comment by andris-sevcenko** [comment]
This has been implemented a while ago.
