### ISSUE TITLE
Pay by check

### ISSUE THREAD

**Issue by sm-md-lg** [craftcms/commerce-stripe#100]
We have a couple of client that would like to have check payment with stripe and I see that Stripe supports [check payment](https://stripe.com/docs/ach) through Plaid (a third party service).  

Does Commerce Stripe support check payment?  If not is it something that is planned on?

**Comment by lukeholder** [comment]
The latest version of the plugin supports these payment methods using the stripe element UI in the payment form. Please make a new ticket if it's not working for you.
