### ISSUE TITLE
Change status on capture?

### ISSUE THREAD

**Issue by circa1977** [craftcms/commerce-stripe#109]
We're using Craft Commerce for a catering service, and our Stripe gateway is set up to Manually Capture payments. We do this because we want to use Stripe to authorize payments when the customer places an order, but we need to review each order to make sure no changes need to be made before capturing the payment.

Is it possible—or, feature request—to change the status of the order when we capture the payment? We have a Paid status that we'd like to have orders set to when they've been captured, but have not yet been Fulfilled.

**Comment by nfourtythree** [comment]
Hi @circa1977 

This is possible, the way to do it would be using the [after capture transaction event](https://docs.craftcms.com/commerce/api/v3/craft-commerce-services-payments.html#event-after-capture-transaction).

This will allow you to tap into when this happens and update the order's status.

Hope this helps, thanks.

**Comment by circa1977** [comment]
Great, I'll explore this. Thank you!
