### ISSUE TITLE
Payment token required?

### ISSUE THREAD

**Issue by nateiler** [craftcms/commerce-stripe#11]
https://github.com/craftcms/commerce-stripe/blob/646750fa7326bd237544bce6d7ddf863889f87e0/src/models/forms/Payment.php#L46

Seems like the only way to use Stripe is to create a payment source and use the token.  However, the order spec allows for raw credit card details to be passed.

https://stripe.com/docs/api#pay_order

**Comment by nateiler** [comment]
I'm (slowly) tracking this down.  I see there is some JS payment form magic going on which is setting this `stripeToken` value ... and therefore getting passed upon submission.

Unfortunately, this isn't desirable for custom front-end logic.

I'll keep digging.

**Comment by andris-sevcenko** [comment]
The decision to ignore any card details is intentional (220bbc5c).

Tokens are accepted as well as of  646750f, however that's not released yet.

**Comment by nateiler** [comment]
Thanks for pointing out what I obviously should have found.

Tokens/Sources make sense ... and it looks like we need to do a little more work on our end.

Would you expect everything in the changlog to get released with Commerce 2 beta 5?

**Comment by andris-sevcenko** [comment]
Yeah, since I changed the Gateway Interface when fixing #12, as soon as Commerce 2 Beta 5 is released, we’ll release this as well.
