### ISSUE TITLE
Allow guest user to make payment

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/commerce-stripe#112]
I have a request related to payment for guest customers.

What I understand is that you must create a user in order to make a payment.

I use this method to create or retrieve a customer stripe

```php
$stripeCustomer = Craft::$app->getModule('commerce-stripe')->customers->getCustomer($order->gatewayId, $user);
```

In addition, in the _stripe_customers_ table, there is the userId field which cannot be null.

I'm trying to understand the reason why we couldn't tie a customer craft to a customer stripe.

Since, a customer is automatically created during the creation of an account, I don't see the reason why it is necessary to associate a user versus a customer.

The problem we have with this is that you have to create a user for a payment made by a guest user. Then I have to delete the user in order to allow him to be able to order again in guest mode. If I don't do this, I will get an error on the next payment saying that the user with the same email address exists.

So this part is unnecessarily complicates our payment flow.

However, maybe there is a reason why you should use a user versus a customer. If so, can you give me more details and maybe a solution to work around this.

If not, would it be an option to modify the plugin in order to use a customer vs a user?

Thank you !

**Comment by nfourtythree** [comment]
Hi @jlachancekffein 

I am not sure if I entirely follow the flow you are going for. 

I am wondering if the following would help? You are able to [make payments on carts or orders that have an outstanding balance](https://docs.craftcms.com/commerce/v3/making-payments.html#paying-outstanding-balance-on-a-cart-or-completed-order). 

Alternatively, it is possible to [load a cart](https://docs.craftcms.com/commerce/v3/loading-a-cart.html) into a customer's session. With the caveat being that if a logged-in user created the cart, then they must be logged in as that user to retrieve it.

Hope this helps.

Thanks.

**Comment by jlachancekffein** [comment]
Here are more details related to the problem mentioned above.

Our project works in headless mode with JWT tokens. So we don't use the server session as such. Instead, we store customer_id in the token. So, to retrieve a customer's cart, we use the customer_id of the token.

But all this is not really related to my question.

Also, instead of using the native Craft Commerce controller for payment, we use the services available to us to manage the complete payment flow.

So the part that interests us is the call to this method:

```
Craft::$app->commerce->getPayments()->processPayment($order, $paymentForm, $redirect, $transaction);
```

This Craft Commerce method dispatch payment management to the Craft / stripe plugin.

In this method, to manage payment with stripe, there is a call made to stripe to register the credit card, and this information is saved in the stripe_customers table. This table is used to save the user, related to the stripe customer. However, it suppose to be a customerId and not an userId. So for now, I have no choice but to create a user to run the entire flow.

Ideally, is the customerId that should have been saved, and not the user. Because, in fact, a customer guest can exist without a user.

So my question is this, does the plugin support payment in customer guest mode? Is there a way not to have saved an entry in the stripe_customers table and make the payment process work ?

**Comment by lukeholder** [comment]
@jlachancekffein Yes the payment controllers support paying for an order as a guest. Just pass the `number` param to the pay controller action. Make a new ticket if you see any issues.
