### ISSUE TITLE
Gateway Response `parameter_invalid_empty` for refund

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce-stripe#114]
We're trying to refund a payment, and have the following screenshot.
![Screen Shot 2020-05-28 at 12 26 44 pm](https://user-images.githubusercontent.com/1221575/83091451-8dc67980-a0de-11ea-9303-dd4e9d6db699.png)

It seems strange this is not in the tooltip info box. If I open that, there are heaps of lines like this:
![Screen Shot 2020-05-28 at 12 27 43 pm](https://user-images.githubusercontent.com/1221575/83091494-a6369400-a0de-11ea-8e43-ff6ebe9d534a.png)

This was a recently (as of today) updated Commerce + Craft site, from Craft 3.3 and Commerce 2 to Commerce 3 + Craft 3.5. As such, the payment was captured on the old versions, and its been tried to be refunded on the new versions. Maybe that's the issue?

Can you advise?

**Comment by nfourtythree** [comment]
Hi @engram-design 

Ths pop-up info issue is likely the same as craftcms/commerce#1467 which we have just pushed a fix for.

I am wondering if this had a knock-on effect on the payment form. If you could update and then let us know if the problem still persists that would be great.

Thanks.

**Comment by engram-design** [comment]
Thanks, will do!

**Comment by lukeholder** [comment]
Closing as stale. Let us know if anything is still an issue with a new ticket. Thanks.
