### ISSUE TITLE
Stripe Charge getting token on test key but then trying to process as live in Stripe

### ISSUE THREAD

**Issue by ajgaunt** [craftcms/commerce-stripe#115]
### Description

We are using the Stripe Charge method for a site (US based cards only) and using Stripe Elements for the card data. This has worked flawlessly on an existing site, but now on a new site when placing a test order, the token is sent and logged in Stripe test mode and shows in the commerce_transactions table, but when the payment tries to place the order it appears in the Stripe live logs with a 400 error and the message "You can not create a livemode source with a testmode token"

### Steps to reproduce

1. Create a Stripe test gateway with test keys
2. Process a payment using Stripe elements (https://stripe.com/docs/stripe-js)

### Additional info

- Craft version: 3.5.2
- PHP version: 7.1.19
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Commerce 3.2.1, Stripe for Craft Commerce 2.3.1.1

**Comment by ajgaunt** [comment]
So I decided to remove the "Live" Stripe gateway and hey presto -- the charge went through. So question is -- WHY is it trying to push through a charge on a separate gateway from the one selected?

**Comment by totov** [comment]
Experiencing the same or a very similar issue with Payment Intents, but the live/test modes are reversed in my situation.

We had two Stripe gateways set up and everything was being processed using the only Gateway we had enabled (the live one), until processing the payment, which then used a disabled (test) Gateway's secret key, and therefore shows up in the error logs in the test account on Stripe. I originally thought maybe it was a caching issue, so tried clearing all the caches, etc, but made no difference.

I've deleted the test Gateway which was previously disabled, which I hope resolves this issue, but this definitely seems like a bug with the latest version.

### Additional info

- Craft version: 3.5.2
- PHP version: 7.3.21
- Database driver & version: MySQL 5.7.31
- Plugins & versions: Commerce 3.2.1, Stripe for Craft Commerce 2.3.1.1

**Comment by lukeholder** [comment]
@jlachancekffein This was fixed in 2.3.2.1

https://github.com/craftcms/commerce-stripe/blob/develop/CHANGELOG.md#2321---2020-11-02
