### ISSUE TITLE
Can't save the same card for 2 customers

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce-stripe#119]
### Description

A customer reported that they got an error when their partner created an account and saved the same card as they had saved in their account.

### Steps to reproduce

1. Save the same card as a payment source for 2 profiles
2. Try to pay with the card

### Additional info

- Craft version: 3.4.x
- Commerce version: 2.2.19
- PHP version: 7.3

**Comment by pdaleramirez** [comment]
I could not replicate the issue on latest version of commerce-stripe plugin. It could have been fixed on recent version of commerce and commerce-stripe plugin. We'll open the issue if the it gets reported again.
