### ISSUE TITLE
Handling No Such User or Test User

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/commerce-stripe#121]
### Description
When you have used a Craft user in test mode it creates a customer on Stripes end. Since that customer id is stored in the database when you switch to live those users perpetually fail payments since the user is in test mode.

When you then delete the customer from test mode on Stripe you get a failed for no customer message.

Can you please handle creating a new customer in these cases?

### Steps to reproduce

1. Make a payment with a customer in Stripe test mode.
2. Switch Stripe to live.
3. Make a payment with the customer in live. (Errors with no such customer but similar one in test.)
4. Delete the test customer from Stripe.
5. Make a payment with the customer in live. (Errors with no such customer.)

### Additional info

- Craft version: 3.5.5
- PHP version: 7.4
- Database driver & version: 8.0.20
- Plugins & versions: Craft Commerce 3.2.3, Craft Commerce Stripe 2.3.1.1

**Comment by lukeholder** [comment]
We added the reset data command that you should run when your site is in production and you don't want the test customers etc to exist:

https://craftcms.com/docs/commerce/3.x/console-commands.html#reset-data
