### ISSUE TITLE
Attaching a PaymentMethod to a Customer is not recommended

### ISSUE THREAD

**Issue by emarthinsen** [craftcms/commerce-stripe#127]
### Description
The implementation of saved payment methods works by creating a payment method in Stripe, then attaching it to a customer (also in Stripe). The Stripe docs warn against this and recommend using SetupIntents instead.

The, somewhat concerning, warning against attaching a payment method is on this page: https://stripe.com/docs/api/payment_methods/attach and it reads:

> To attach a new PaymentMethod to a customer for future payments, we recommend you use a SetupIntent or a PaymentIntent with setup_future_usage. These approaches will perform any necessary steps to ensure that the PaymentMethod can be used in a future payment. **Using the /v1/payment_methods/:id/attach endpoint does not ensure that future payments can be made with the attached PaymentMethod**. See Optimizing cards for future payments for more information about setting up future payments.

_(The emphasis is my own.)_

### Additional info

I'm noticing this behavior in version 2.3.0 of the plugin. I noticed this behavior by looking at the log files in the Stripe admin.

**Comment by lukeholder** [comment]
Good news! Setup intents is now the default behavior for creating payment sources.

See our announcement:

 https://craftcms.com/blog/commerce-4-3-stripe-4
