### ISSUE TITLE
Update readme so it's clear from first sentence this is the latest Stripe gateway plugin :)

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce-stripe#128]
### Description
Adding a clear statement at the top of the readme would remove any element of doubt that you had the latest/correct version of the Stripe payment gateway. Thanks : )

**Comment by lukeholder** [comment]
@j-greig there was only even one Stripe gateway plugin, this one. Before that, Stripe was a gateway built into Commerce 1 (no plugin). Unless I am misunderstanding the issue?

**Comment by j-greig** [comment]
Sorry think I meant to post this on the old PayPal plugin, please ignore me 😅
