### ISSUE TITLE
Compatibilty with API 05-21-2018

### ISSUE THREAD

**Issue by pixelbeatcreative** [craftcms/commerce-stripe#13]
Stripe recently updated their API, will this plugin still work?

**Comment by andris-sevcenko** [comment]
Stripe allows requesting a specific version of the API (https://github.com/craftcms/commerce-stripe/blob/master/src/gateways/Gateway.php#L185), so yeah.

Seems like the new API version has some updates to subscription data structure, so we'll switch to that after we've had some time to test the changes. Until then, this plugin will keep on using the 2018-02-06 API version.
