### ISSUE TITLE
Direct Debit optiion in Stripe for Subscriptions

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/commerce-stripe#130]
We have been asked multiple times recently about Direct Debit payments with Craft Commerce Subscriptions.

As Stripe is the only payment gateway that you support, I did some googling and it looks like Stripe supports direct debits - https://stripe.com/docs/billing/subscriptions/bacs-debit

It would be great if Craft Commerce could support this!

Thanks :)

**Comment by jamiepittock** [comment]
@johnwbaxter I was wondering if you got anywhere with Direct Debits and Craft Commerce?

**Comment by johnwbaxter** [comment]
Hey @jamiepittock, no I didn't actually. One client went and signed up to GoCardless without even checking with us first so obviously that's going nowhere fast, and the other client are still with their existing DD supplier and haven't reminded me since so I haven't looked into it further. I'd love to have some paid time to take a look at it though!!

**Comment by jamiepittock** [comment]
Thanks @johnwbaxter. I'll let you know if we pursue it and get anywhere!

**Comment by amici-infotech** [comment]
Hey. This issue is Open from 2020 so no hopes? Is someone achieve something maybe an extended gateway to support bacs?

**Comment by lukeholder** [comment]
This is possible with the latest 4.1.1 - any stripe payment source that can be saved in stripe can be used for subscriptions. Thanks.

**Comment by amici-infotech** [comment]
@lukeholder Do we have any example on how to achieve Direct Debit payment with updated stripe plugin? I tried to use it, it works with PaymentIntents but not with SetupIntents. Direct Debit payment methods like BACS is not showing in SetupIntents. It works with PaymentIntents though.
