### ISSUE TITLE
Successful order marked as Attempted Payment & 'Partial' Paid Status

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce-stripe#137]
### Description
I have just come across an order in the Attempted Payments area with a Paid Status of `Partial`. 

Checking the transaction logs, the payment has all gone through successfully and I can see it as a complete payment in the Stripe account. 

So I have no idea why the order was not completed in the CMS, and marked as `Partial`?!

This is the only instance I've seen of this, on a site that has a high volume of orders. 

### Additional info

- Craft version: 3.4.9
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.32
- Plugins & versions: 2.2.17

**Comment by nmenglund** [comment]
Hi, I have seen the same issue while debugging an (I think) unrelated case -- did you find any answers for this?

**Comment by iamtompickering** [comment]
@nmenglund sadly not found anything on this. Although it hasn't happened again. Such a strange issue...

**Comment by pdaleramirez** [comment]
@iamtompickering The Partial status happens when the customer don't get redirected to the order complete page on payment complete. It could be the customer closes the modal window or a browser crash before it gets redirected to the site's order complete page.
