### ISSUE TITLE
Accept Pull Request to add/modify SubscriptionForm

### ISSUE THREAD

**Issue by nateiler** [craftcms/commerce-stripe#14]
There are a handful of additional attributes when creating a Subscription (https://stripe.com/docs/api#create_subscription).  Would you entertain a pull request which includes some of these on a Stripe `SubscriptionForm` class?  Granted they may not be applicable, but it would be nice for a developer to modify these via an event.

**Comment by andris-sevcenko** [comment]
We would definitely entertain a pull request :)
