### ISSUE TITLE
Ability to style Stripe card

### ISSUE THREAD

**Issue by tnerbovik** [craftcms/commerce-stripe#140]
Option to add own style definition to Stripe card form.

**Comment by nfourtythree** [comment]
Hi @tnerbovik 

This [question was asked over on stack exchange](https://craftcms.stackexchange.com/questions/30679/customizing-stripe-payment-form-for-craft-commerce-2) for which we have [provided an answer](https://craftcms.stackexchange.com/questions/30679/customizing-stripe-payment-form-for-craft-commerce-2/33168#33168).

Thanks!
