### ISSUE TITLE
Subscription Payment history not updating when user subscribes to a plan

### ISSUE THREAD

**Issue by fordchristopher** [craftcms/commerce-stripe#144]
Hello, I am using Craft version 3.5.14, Craft commerce version 3.2.11 and commerce-stripe 2.3.2.1.

I have set up my webhook with stripe so that stripe can attempt to send webhooks to craft for appropriate updates. I have enabled many webhook events trying to get this to work:

invoice.updated
invoice.sent
invoice.finalized
payment_intent.succeeded
order.payment_succeeded
invoice.paid
charge.updated
charge.succeeded
charge.captured
price.created
price.deleted
price.updated
plan.created
customer.subscription.created
customer.updated
invoice.payment_failed
customer.subscription.updated
invoice.created
plan.updated
plan.deleted
customer.subscription.deleted
invoice.payment_succeeded
source.failed
source.chargeable
source.canceled

I know that the webhooks are being received by craft because I can see the status of the webhooks on the stripe dashboard, and when I am working locally I am using ultrahook and can see a status of 200 for each webhook.

When I subscribe to a plan, the subscription is created, but there is no payment in the plan until I click on "Refresh payment history". I cannot see it in the CMS nor can I find it in a module with PHP. Once the buttons is pressed, the payment shows up and everything works as expected.

Is this updated via webhooks? Am I missing the correct webhook event? How can I get this payment to be present without having to click this button?

![Screen Shot 2021-01-22 at 4 08 52 PM](https://user-images.githubusercontent.com/29003743/105548012-242e5780-5ccd-11eb-9c47-351cabfdc210.png)

Thank you!

**Comment by terryupton** [comment]
@Chris7Ford did you manage to resolve this? I am seeing the same issue.

**Comment by lukeholder** [comment]
This will be fixed in the next release. I will let you know once it is out here.
