### ISSUE TITLE
Cannot change card details for an active customer subscription

### ISSUE THREAD

**Issue by jakepm** [craftcms/commerce-stripe#146]
### Description

Stripe Commerce Lite with Stripe Gateway, is missing the ability to change card details for an active subscription/customer. Given that this is a **guaranteed eventuality** for any long-term subscription, I believe this should be considered a bug rather than a feature request. 

We've just had to put an entire project on hold because of this missing feature which we wrongly assumed _must_ be part of the Stripe Gateway feature set. The client is deciding whether to stick with Craft and handle card changes manually, or whether to skip Craft Commerce entirely and integrate directly with Stripe despite the extra cost & maintenance burden. Understandably, they are struggling to understand how this feature is missing and whether they should have gone with our recommendation to use Craft Commerce in the first place.

PS. Not having an eta on when this may be resolved, makes it a tricky decision for both our agency and the client. It would help greatly if we can assure them that manual interventions will only be required for 6 months, for example.

### Steps to reproduce

1. Setup Craft with Commerce Lite & Stripe Gateway
2. Create a customer with a subscription 
3. Fast-forward to moment where card inevitably expires
4. Forced to manually intervene and handle change of card details via Stripe

### Additional info

- Craft version: 3.6.*
- PHP version: 7.4
- Database driver & version: MySQL 5.6
- Plugins & versions: Craft Commerce (Lite), Stripe for Commerce

**Comment by lukeholder** [comment]
Hi @jakepm 

Once Commerce 3.3 is out (soon) the things you observe are high on our list to fix. 

Right now we expect the default card to be charged in their Stripe account, for the subscription. If you allowing only one card in the UI, which they can remove before adding their new one would switch the default card. We know this is not ideal and we have started working on the following:

- Card per subscriptions. Switching cards.
- Update card and other subscription email
- Syncing cards / payment source / customers from Stripe.

Thanks for reporting and please keep track here: https://github.com/craftcms/commerce/issues/1336

**Comment by jakepm** [comment]
Thanks for the update @lukeholder - this is great to hear and our client will be very pleased.
