### ISSUE TITLE
Strong Customer Authentication (SCA) for EU Payments

### ISSUE THREAD

**Issue by andrewhawkes** [craftcms/commerce-stripe#148]
### Description

I've just put a payment through using the live settings and it's all working. I have just received an email from Stripe with the following:

"
Thank you for choosing Stripe! We’re writing because we noticed your account is impacted by a regulatory requirement called Strong Customer Authentication (SCA). SCA requires two-factor authentication on many payments in Europe. Payments that are not authenticated are at risk of being declined by your customers’ banks.

Your account ********* has payments (like this one) in live mode using the Charges API, which does not support the authentication requirements of SCA. We recommend reaching out to your plugin developer about using one of our SCA-ready integration paths to avoid more declined European payments.
--
"

More info https://stripe.com/en-gb/payments/strong-customer-authentication

So I am wondering if this can be implemented?

**Comment by lukeholder** [comment]
@andrewhawkes Are you using the Stripe Payment Intents gateway? The charge gateway is deprecated inside the plugin so you can switch it over in your stripe gateway settings.
