### ISSUE TITLE
Allow localization in paymentForm.js

### ISSUE THREAD

**Issue by simonkuran** [craftcms/commerce-stripe#152]
This might be a tricky request, but I would be nice to not have to build something from scratch for such a small change. It would be handy if paymentForm.js could pass the localization to Stripe for credit card fields and errors. [Stripe supports translations](https://stripe.com/docs/js/appendix/supported_locales). [Line 38 of paymentForm.js](https://github.com/craftcms/commerce-stripe/blob/develop/src/web/assets/intentsform/js/paymentForm.js#L38) would need to be able to pass Stripe's `locale` parameter, something like this `var elements = this.stripeInstance.elements({locale: 'fr'});`. Obviously this would need to be dynamic so I see where this could be difficult. Is there a possibility of this feature being added in the future?

**Comment by lukeholder** [comment]
The latest payment intents elements for supports design customization and relabelling of some UI. Please check out 4.1+
