### ISSUE TITLE
Failed webhooks for Subscription with Payment Method Issue

### ISSUE THREAD

**Issue by peteeveleigh** [craftcms/commerce-stripe#155]
I first raised this issue on the Commerce Github but it's been closed and doesn't seem to be getting any attention.
https://github.com/craftcms/commerce/issues/2063

I'm raising it here because it is a Commerce Stripe issue. and appears to be similar to craftcms/commerce-stripe@d71dd17

When a subscription has been moved into the "Payment Method Issue" section of the Subscriptions CP any Stripe webhooks for that subscription fail.

In our case, we have a couple of customers with subscriptions that failed payments. It looks like the payment method has then been updated. But when Stripe sends the webhook, it causes an error because the subscription cannot be found.
Stripe continues to send the webhook at decreasing time intervals.

The log says that the subscription cannot be found and refers to line https://github.com/craftcms/commerce-stripe/blob/c5c2537fe6f2882af9bc93fa77de8358e77d3455/src/base/SubscriptionGateway.php#L604

The problem, I think, is that the subscription has been marked as suspended and so isn't retrieved by the Subscription::find() query once the payment issue is resolved.

    do {
            // Handle cases when Stripe sends us a webhook so soon that we haven't processed the subscription that triggered the webhook
            sleep(1);
            $subscription = Subscription::find()->reference($subscriptionReference)->one();
            $counter++;
        } while (!$subscription && $counter < $limit);

        if (!$subscription) {
            throw new SubscriptionException('Subscription with the reference “' . $subscriptionReference . '” not found when processing webhook ' . $data['id']);
        }
It would appear that the query that is meant to fetch the subscription fails. Is this perhaps because of a status?

Expected behavior
I'd expect the subscription to be reactivated and moved out of the Payment Method Issue section, and the webhook to succeed.

Additional info

Craft version: 3.6.9
Commerce version: 3.2.17
Commerce Stripe version: 2.3.2.1

**Comment by fantasticmachine** [comment]
Is there any movement on this? It’s quite a major issue and is affecting a number of people.

In our case we have quite a few subscriptions now and we are having to monitor any failures and manually adjust the database to allow the subscriptions to be continued. 

Obviously this is not a great situation.

**Comment by fantasticmachine** [comment]
Anything?

**Comment by lukeholder** [comment]
Just getting commerce 3.4 beta out and will look at this tomorrow. Thanks.

**Comment by fantasticmachine** [comment]
Hi Luke,

Thanks…. I think  I sent that email from the wrong email account. Should have been from ***@***.*** ***@***.***>


--

Moresoda
Refreshing Digital Experience

16 Old Bond Street, Bath, BA1 1BP
t. 01225 808630  m. 07974 837505  w. moresoda.co.uk <http://moresoda.co.uk/>

Follow us at twitter.com/moresoda <https://twitter.com/moresoda> or find me at linkedin.com/in/peteeveleigh <https://www.linkedin.com/in/peteeveleigh>

_________________________________________________________

Moresoda Design Ltd. Company no. 6432433

**Comment by johnwbaxter** [comment]
@lukeholder Did this get fixed in a Commerce release? Or, is it unfixed do we know? It's a pretty big issue so fingers crossed it got fixed and I can just update!

**Comment by AugustMiller** [comment]
@johnwbaxter I believe this fix has been present since at least version 3.0. All Subscription queries that are used in conjunction with webhooks explicitly remove the status constraint, which appeared to be the source of the bug. I will wait for Luke to chime in with additional context!

**Comment by lukeholder** [comment]
I believe this is fixed, and this ticket was not updated. When successful invoice payments happen the subscription is retrieved without the status: https://github.com/craftcms/commerce-stripe/blob/4.1.1/src/base/SubscriptionGateway.php#L584
