### ISSUE TITLE
Add event to modify the PaymentIntent confirm request / or expand by defualt?

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce-stripe#157]
Would you consider adding another event to modify the request data used to confirm a PI (as you can already do with a purchase, refund etc), we would like to be able to expand objects, namely the `balance_transaction` so that we can get the full details on the fee's stripe charges.

We would need the ability to modify the payload here.

https://github.com/craftcms/commerce-stripe/blob/40a1454b7af521e31f2fa62f0e0e67401677c25c/src/gateways/PaymentIntents.php#L564

Not sure if you would want this to be a completely new event, or if it could be handled in the existing `BuildGatewayRequestEvent`.

Alternatively you could include it by default, it does provide some really useful data which would be super useful to be able to access without having to make an additional api request to Stripe:

```php
$stripePaymentIntent->confirm([
    'return_url' => UrlHelper::actionUrl('commerce/payments/complete-payment', ['commerceTransactionId' => $transaction->id, 'commerceTransactionHash' => $transaction->hash]),
    'expand' => ['charges.data.balance_transaction']
]);
```

Happy to add this our send as a PR if you think its a goer?

**Comment by codyjames** [comment]
We need this as well. Since Stripe fees can be inconsistent (Canadian cards have an added 1% fee) we need to know exactly what the fee was on an order.

**Comment by lukeholder** [comment]
We added `craft\commerce\stripe\gateways\PaymentIntents::EVENT_BEFORE_CONFIRM_PAYMENT_INTENT`. ([#221](https://github.com/craftcms/commerce-stripe/pull/221)) in 3.0.2
