### ISSUE TITLE
Payment by bancontact failed

### ISSUE THREAD

**Issue by JoeriE** [craftcms/commerce-stripe#158]
### Description

I'm trying to implement the Bancontact payment method. Everything goes well until the moment I'm redirected back to the website (shop/checkout/payment). I get a correct success response when I retrieve the payment intent. I insert the payment method ID in a hidden field `paymentMethodId` and then submit the payment form.

```
        stripe.retrievePaymentIntent(clientSecret).then(function(response) {
            if (response.error) {
                // Handle error
            } else if (response.paymentIntent && response.paymentIntent.status === 'succeeded') {
                console.log(response);
                // Handle successful payment
                var form = document.getElementById('payment-form');
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'paymentMethodId');
                hiddenInput.setAttribute('value', response.paymentIntent.payment_method);
                form.appendChild(hiddenInput);

                // form.submit();
            }
        });
``` 

Then I get this errors when I submit the form:
`The provided bancontact PaymentMethod cannot be used again. It was used in a previous PaymentIntent or SetupIntent to set up a sepa_debit PaymentMethod, which can be used for multiple payments. To find the ID of the sepa_debit PaymentMethod, list the sepa_debit PaymentMethods associated with the Customer used to set up this PaymentMethod `

Is there any documentation how to implement the Bancontact payment method. The implementation of the credit card is working fine.

Thanks in advance!
Best wishes,
Joeri 

### Additional info

- Craft version: 3.7.7
- PHP version: 3.4.1

**Comment by pdaleramirez** [comment]
@JoeriE This is a Bancontact issue, It could be that you are trying to send an existing paymentIntent ID. Commerce doesn't have specific docs on how to implement Bancontact payment gateway. I would suggest to checkout commerce-stripe plugin to see how it is implemented.
