### ISSUE TITLE
Gateway Response This value must be greater than or equal to 1.

### ISSUE THREAD

**Issue by useralberto** [craftcms/commerce-stripe#159]
### Description

Hi, we are trying to make payments through stripe but it only responds _This value must be greater than or equal to 1._

![Screenshot_20210816_215209](https://user-images.githubusercontent.com/31530471/129656336-936a406d-c183-43db-8cb0-46ebe92cca2d.png)

![Screenshot_20210816_215326](https://user-images.githubusercontent.com/31530471/129656459-bc1ecbc1-dfa3-49c1-8edc-107dcaecd1cb.png)

### Steps to reproduce

1. The steps indicated in the documentation https://github.com/craftcms/commerce-stripe have been applied.

### Additional info

- Craft version: Craft Pro 3.7.8
- PHP version: 7.4.5
- Database driver & version:  MySQL 5.5.5
- Stripe for Craft Commerce 2.3.2.1

**Comment by codyjames** [comment]
@useralberto Mind telling me how this was resolved? It started happening out of the blue and I can't figure it out.

**Comment by useralberto** [comment]
Hello @codyjames , the problem we had was related because we tried to implement the partial payment option in commerce, but this did not fit our needs, when we updated craft stopped working the payment option and showed the error which is mentioned, we discovered that the option in the `config/commerce.php` file was still true `allowPartialPaymentOnCheckout` and the payment process did not specify the amount is why the error occurred, just change the value from true to false and it worked.

but it should be noted that this occurred once we updated craft because in previous versions it worked fine even if it was set to true.

**Comment by codyjames** [comment]
@useralberto It feels like Craft is loading an old/completed cart for me rather than a new cart. This is causing the zero dollar attempted charge which throws an error with Stripe.
