### ISSUE TITLE
Adding payment sources creates a new customer and attaches the source to that

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce-stripe#161]
This might be related to https://github.com/craftcms/commerce-stripe/issues/127, but I'm not sure.

### Description
When customers add a new payment source, Stripe is creating a new customer at the same time and attaching the payment source to that. So when subscription renewal is due, the payment fails because the subscription is using the original customer along with the expired payment source attached to that.

### Steps to reproduce
1) Customer uses 'commerce/payment-sources/delete' form to delete old card. Checking the customer in Stripe, the card is deleted.
2) Customer uses 'commerce/payment-sources/add' form to add new card. But what happens here is a new customer is created within Stripe, with the new card attached to that.
3) Stripe attempts to take the subscription renewal payment using the original customer (that's who the subscription is with, after all) but there is no card to take payment with, so it fails.

### Additional info

- Craft version: 3.6.15
- PHP version: 7.3.6
- Database driver & version: MySQL 5.7.35
- Commerce version: 3.3.2
- Stripe version: 2.3.2.1

**Comment by lukeholder** [comment]
I can not reproduce this as of Commerce Stripe 2.4.2, can you please update and open a new ticket if this is still an issue.
