### ISSUE TITLE
Loop in Recent Migration takes a Long Time to Run on Large Datasets

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce-stripe#185]
### Description
We're working on upgrading to the most recent Craft & Commerce versions and ran into a bit of a problem with a long running migration. I should clarify that it does eventually run for us, but it takes 45 minutes to complete with our dataset. 

We have roughly 700k rows in `craft_commerce_transactions`, but only ~9k rows in `craft_stripe_paymentintents`. Anyways I was able to track the problem down to this [file](https://github.com/craftcms/commerce-stripe/commit/f6fe8861b76aadef3e4ef47f0c067fbcb6c2b791#diff-917c307c4f1cd9ac40b46a09ad0d60576aba856df74f93bcb691e49175cda029). Specifically this loop:

```php
        $transactions = (new Query())
            ->select(['reference', 'hash'])
            ->from(['{{%commerce_transactions}}'])
            ->where(['LIKE', 'reference', 'pi_%', false]) // they are using a payment intent identifier
            ->andWhere(['gatewayId' => $gatewayIds])
            ->all();

        foreach ($transactions as $transaction) {
            $this->update('{{%stripe_paymentintents}}', ['transactionHash' => $transaction['hash']], ['reference' => $transaction['reference']]);
        }
```

For us it's just iterating over 700k rows regardless of if anything should be updated. I was thinking about opening up a PR to turn this into a bit more performant of a query, but I wanted to start here because I wasn't sure the best path forward:

1. I think the best case scenario is updating that portion of the migration to resemble something like this query. In our dataset that only takes 3 seconds to run:

```mysql
UPDATE craft_stripe_paymentintents csp 
	INNER JOIN craft_commerce_transactions cct ON csp.reference = cct.reference COLLATE utf8_general_ci
	INNER JOIN craft_commerce_gateways ccg ON cct.gatewayId = ccg.id AND ccg.handle = 'stripePaymentIntents'
SET csp.transactionhash = cct.hash
WHERE cct.reference LIKE 'pi_%';
```

2. An alternate solution that wouldn't be as performant, but likely much quicker is flipping the loop to loop over records from the `stripe_paymentintents` table rather than the larger table. Or including a join to the payment intents table on the initial select to filter out transactions that don't matter.

3. My least favorite idea is just making this part of the migration optional and then adding a console command to repair the paymentintents table that could happen asynchronously.

### Steps to reproduce
_I can provide our database if that'd be helpful for this`

1. Add 700k transactions into `craft_commerce_transactions` 
2. Run migration `m210903_040320_payment_intent_unique_on_transaction` on that dataset
3. Notice that migration takes 45 minutes to run

### Additional info

- Craft CMS version: Craft Pro 3.7.18.2
- Stripe for Craft Commerce version: Upgrading from 2.3.2.1 to 2.4
- PHP version: 7.3.19
- Database driver & version: Mysql 5.7.33
- Plugins & versions:

```
Amazon S3	1.3.0
Cookies	1.1.15
Craft Commerce	3.4.6
Doxter	3.5.1
Instant Analytics	1.1.12
Linkit	1.1.12.1
oEmbed	1.3.13
Redactor	2.8.8
Retour	3.1.65
SEOmatic	3.4.17
Similar	1.1.5
Stripe for Craft Commerce	2.3.2.1
```

**Comment by cole007** [comment]
Echoing this issue on a Stripe Payment Intents table with 23k records.
Updating and subsequent migration is a real resource bottleneck and blocking us making other releases on our site.

Raised via support. See CraftCMS support ticket #17107

**Comment by lukeholder** [comment]
@cole007 @dhahn 

Just pushed a fix to the performance of the migration. Sorry about that.
We will be cutting a new release very soon and will update you here once it is out.

**Comment by lukeholder** [comment]
Stripe 2.4.1 is out with this fix.

**Comment by ragnarfrosti** [comment]
I just wanted to reopen this issue as it seems that the solution does not fix the performance on my local machine at least (Nitro 2).

In our transactions table there are 80.000 rows and in the paymentintents table there are ~7000 rows and the migration of the following query took about 30minutes to run using the migration-console commands:

```
    > execute SQL: UPDATE {{%stripe_paymentintents}} [[pi]]
INNER JOIN {{%commerce_transactions}} [[t]] ON [[t.reference]] = [[pi.reference]]
SET [[pi.transactionHash]] = [[t.hash]]
WHERE [[pi.transactionHash]] IS NULL ...
 done (time: 1803.781s)
```

And on my colleague's machine it's been running for over 60 minutes now on a copy of the same DB.

**Comment by ragnarfrosti** [comment]
Update: The migration in production took 2 hours.....
