### ISSUE TITLE
Creating customer error in 2.4.x

### ISSUE THREAD

**Issue by adrienpicard** [craftcms/commerce-stripe#186]
### Description
The new validation rules changed in c127a5fd7af9ecc47b7a5867c460529f51e78a9f introduces a bug when creating/fetching customers.

### Steps to reproduce
1. Add payment sources using `actions/commerce/payment-sources/add`
2. When the customer doesn't exist and gets created, the call returns a `Could not fetch Stripe customer: Could not save customer: Gateway Id \"xx\" has already been taken.`

### Additional info

- Craft CMS version: 3.7.21
- Stripe for Craft Commerce version: 2.4.1
- PHP version: 7.4

**Comment by espensgr** [comment]
We are having the same problem.

When i try to revert to 2.4.0 version i just get this in terminal:
`Stripe for Craft Commerce is installed with schema version of 2.4.0 while 2.4.1 was expected.`

Any way to force this? Change this manually in the `project.yaml` file?
As of now the costumers cant pay in the webshop, so would like a fix on this pretty fast.

**Comment by Tlueders** [comment]
We ran into this issue today as well after testing the update. Same error and steps provided by adrienpicard. Except we were hitting our `/actions/commerce/payments/pay` route to complete an order.

**Comment by adrienpicard** [comment]
@espensgr If you want to downgrade, in `composer.json` try `"craftcms/commerce-stripe": "2.4.0 as 2.4.1"` and run composer update. That should do it.

**Comment by samhibberd** [comment]
Same issue for us, testing the update, hitting `/actions/commerce/payments/pay`, can also confirm that 2.4.0 does not have the same issue.

Shout if there is anything specific you need to assist in debugging.

**Comment by lukeholder** [comment]
This has been fixed in 2.4.2 sorry about that!
