### ISSUE TITLE
Error when updating from 2.3.2.1 to 2.4.2

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce-stripe#187]
When trying to update from 2.3.2.1 to 2.4.2 the migration fails with the following output

```
*** applying m210903_040320_payment_intent_unique_on_transaction
    > execute SQL: UPDATE {{%stripe_paymentintents}} [[pi]]
INNER JOIN {{%commerce_transactions}} [[t]] ON [[t.reference]] = [[pi.reference]]
SET [[pi.transactionHash]] = [[t.hash]]
WHERE [[pi.transactionHash]] IS NULL ...**Exception: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='**
The SQL being executed was: UPDATE `craft_stripe_paymentintents` `pi`
INNER JOIN `craft_commerce_transactions` `t` ON `t`.`reference` = `pi`.`reference`
SET `pi`.`transactionHash` = `t`.`hash`
WHERE `pi`.`transactionHash` IS NULL (/Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `craft_s...')
#1 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `craft_s...')
#2 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/craftcms/commerce-stripe/src/migrations/m210903_040320_payment_intent_unique_on_transaction.php(50): yii\db\Migration->execute('UPDATE {{%strip...')
#4 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\stripe\migrations\m210903_040320_payment_intent_unique_on_transaction->safeUp()
#5 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/craftcms/cms/src/console/controllers/MigrateController.php(385): yii\console\controllers\BaseMigrateController->migrateUp('m210903_040320_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#11 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#12 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#13 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#15 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /Users/pete/Projects/Somename/clientname/clientname-craft-3/build/craft(23): yii\base\Application->run()
#17 {main}
*** failed to apply m210903_040320_payment_intent_unique_on_transaction (time: 0.011s)
```

### Additional info

- Craft CMS version: 3.7.23
- Stripe for Craft Commerce version: 2.3.2.1
- PHP version: 7.4.34
- Database driver & version: MySQL 5.7.34

**Comment by angrybrad** [comment]
Sounds like you've got some mixed (and incompatible) collations in your database tables/columns.

Restore from a pre-update attempt database backup, run https://craftcms.com/docs/3.x/console-commands.html#db-convert-charset, which will set all of them to charset/collation you tell it to, then try the update again and it should work.

**Comment by fantasticmachine** [comment]
Hi Brad,

Pre which update?

I don’t think there’s any chance I’d be able to restore from an old database since it’s a busy ecommerce site so orders, customers etc would be out of sync. Also there have been many updates performed on the site.

Although the Stripe gateway has only recently been installed. This has come about as we switch from using Barclays EPDQ to Stripe.

Do you think removing the Stripe gateway completely and then reinstalling fix this?

Cheers
Pete

**Comment by angrybrad** [comment]
> Pre which update?

Pre before you got this error, same as with any other failed update attempt. You want to make sure don't run the update again when the database is in a half-completed migration state.

https://craftcms.com/knowledge-base/failed-updates#a-migration-error-can-occur

> I don’t think there’s any chance I’d be able to restore from an old database since it’s a busy ecommerce site

But it looks like you got this error locally?

> /Users/pete/Projects/Somename/clientname/clientname-craft-3

For production, you'd SSH in before doing the update, run that console command to convert charset/collation, then do the update.

-Brad

**Comment by fantasticmachine** [comment]
Ah I see what you mean.
yes it was local and I reverted to a copy of the db before I tried that failed update to the plugin

**Comment by fantasticmachine** [comment]
FYI I’m getting the exact same problem on another site when I try to apply this update. We haven’t made any changes to the DB schema on either site and they are both on the latest versions of everything.

**Comment by fantasticmachine** [comment]
Further FYI

I’ve applied the updates from 2.3.2.1 to 2.4.2 individually, i.e. 2.3.2.2, 2.4.0, 2.4.1, 2.4.2 and they were successful. So it seems the issue is going from 2.3.2.1 direct to 2.4.2

**Comment by angrybrad** [comment]
For any of the sites you're getting this on, have you ran the https://craftcms.com/docs/3.x/console-commands.html#db-convert-charset command?

**Comment by fantasticmachine** [comment]
> For any of the sites you're getting this on, have you ran the https://craftcms.com/docs/3.x/console-commands.html#db-convert-charset command?

Nope. I also tested this again late yesterday. 
Trying to update from 2.3.2.1 to 2.4.2 causes the error.
But updating from 2.4.1 to 2.4.2 is fine.
