### ISSUE TITLE
How to Disable 3D secure authentication on stripe gateway with craft commerce.

### ISSUE THREAD

**Issue by w3care25** [craftcms/commerce-stripe#192]
Hi, All
I am implementing the subscription process with craft commerce through "Stripe gateway" but am not getting any successful payment on stripe gateway, When I check my payment on stripe gateway, it is always showing incomplete, I have checked my error logs, It is showing some kind of error "The PaymentIntent needs to be authenticated by 3D Secure".

So please let me know how can I disable this 3D secure authentication on my craft site or any other solution.

![Screenshot (27)](https://user-images.githubusercontent.com/8121267/154794780-8c23d9e9-d1c7-4dbf-94a6-8c8a74791df3.png)

### Additional info

- Craft CMS version: 3.7.27.2
- Stripe for Craft Commerce version: 2.4.3
- PHP version:7.4
- Database driver & version:
- Plugins & versions:

Thanks

**Comment by fantasticmachine** [comment]
3D Secure 2 is a requirement so turning it off isn't going to be an option for you.

It may be that you need to set up a webhook with the appropriate events to handle 3DS2 authentication

**Comment by cliveportman** [comment]
Does anyone have any examples of docs for 3D Secure 2 with this?

**Comment by cliveportman** [comment]
Thanks. So, I use the normal payment form, and submit it with the paymentMethodId like in the docs. Then the webhooks take care of the rest?

**Comment by fantasticmachine** [comment]
Hmm It should work with Subscriptions too as far as I know. I have certainly used it with Commerce Subscriptions but I no longer have access to that site to confirm how it's set up.

**Comment by cliveportman** [comment]
I'll try a clean install with no other plugins or my module and see if that works. I'm using the example templates.

**Comment by migswd** [comment]
> I'll try a clean install with no other plugins or my module and see if that works. I'm using the example templates.

Hi Clive.
I am running into the same problem as you.
This works with products. It doesn't work with subscriptions.

Did you found a solution?

**Comment by lukeholder** [comment]
To support 3DS fully we suggest using the latest version of Commerce and the Stripe plugin. Thanks.
