### ISSUE TITLE
[Documentation] stripe.createPaymentMethod() signature

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/commerce-stripe#196]
### Description

In the implementation docs, here: https://github.com/craftcms/commerce-stripe near the bottom of the page, it says:

>Finally, add a form listener that uses the submitted card details to [create a payment method](https://stripe.com/docs/js/payment_methods/create_payment_method) and pass in optional billing details:

And the example below has:

```js
...
stripe.createPaymentMethod('card', card, paymentData).then(function(result) {
...
```

But the documentation as linked above, [here](https://stripe.com/docs/js/payment_methods/create_payment_method) states that `stripe.createPaymentMethod()` should have a single parameter instead of 3 as above. This is probably down to API versioning, so if it's not possible to link to the older version of Stripe's docs where this method has 3 parameters, it should be made clearer what's going on.

### Steps to reproduce

N/A

### Additional info

- Visible on the current `HEAD` of develop or commit hash `3e2d180a5d516ac252d1510662e08f9d64eed6e0` (at time of writing).

**Comment by pdaleramirez** [comment]
@rob-baker-ar This is not a Stripe JavaScript but JS code from the plugin: https://github.com/craftcms/commerce-stripe/blob/e7cd3cb240a2e85ccacb335a77a4d5bef76e0ee3/src/web/assets/intentsform/js/paymentForm.js#L141

**Comment by rob-baker-ar** [comment]
The plugin code in `paymentForm.js` does not define `createPaymentMethod()` it's a method on `this.stripeInstance`. The line you refer to **is** a call to the Stripe JS library. This can be seen a bit further up in the file you refer to:

https://github.com/craftcms/commerce-stripe/blob/e7cd3cb240a2e85ccacb335a77a4d5bef76e0ee3/src/web/assets/intentsform/js/paymentForm.js#L3
