### ISSUE TITLE
Add ability to hook into the custom creation

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-stripe#198]
https://github.com/craftcms/commerce-stripe/blob/c127a5fd7af9ecc47b7a5867c460529f51e78a9f/src/services/Customers.php#L59

This would allow developers to add additional data to the customer.

- [ ] We should also add customer name by default.

**Comment by stevecomrie** [comment]
I've submited a PR that facilitates this request - https://github.com/craftcms/commerce-stripe/pull/215

**Comment by lukeholder** [comment]
Fixed in #233
