### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by olsp** [craftcms/commerce-stripe#21]
In the gateway settings for Stripe I need to fill in 3 fields, API Key, Publishable API Key and Signing secret.
But Stripe only gives me the publishable and the secret key, what do I need to fill in the API Key field?
https://stripe.com/docs/keys

**Comment by andris-sevcenko** [comment]
I guess the documentation should be more clear about this as well as the setting names. The API key is now called the "Secret key" in the dashboard.

The webhook signing secret is for webhooks (https://github.com/craftcms/commerce-stripe#webhooks)

I'll leave this issue open so I don't forget to update the docs.
