### ISSUE TITLE
getUser() called instead of getCustomer() in src/gateways/PaymentIntents.php 

### ISSUE THREAD

**Issue by scaramanga-support** [craftcms/commerce-stripe#210]
### Description

When making a payment I get a flash error message reading "The `Order::getUser()` is deprecated, use the `Order::getCustomer()` instead."

I have been able to resolve this by changing line 487 of src/gateways/PaymentIntents.php to reference `getCustomer()` instead of `getUser()`.

If the above is the correct way to fix this, then please can you implement that change? My initial testing indicates that won't have any further repercussions.

### Steps to reproduce

1. Ensure markup for displaying flash messages is present.
2. Attempt a payment using Stripe payment gateway.

### Additional info

- Craft CMS version: 4.0.4
- Stripe for Craft Commerce version: 3.0.1
- PHP version: 8.0.8
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Blitz (4.1.4); Cookies (4.0.0); Commerce (4.0.3); Field Manager (3.0.0-beta.1); Freeform (4.0.0-beta.12); Navigation (2.0.2); Redactor (3.0.0); Redactor Custom Styles (4.0.1); Retour (4.0.1); SEOmatic (4.0.2); Servd Assets and Helpers (3.0.2); Sprig (2.0.1); Super Table (3.0.0-beta.6); GeoMate (2.0.0)

**Comment by robzor** [comment]
HI @nfourtythree is this version going to be released soon?
