### ISSUE TITLE
Payment Method Id cannot be blank.

### ISSUE THREAD

**Issue by hassanmah** [craftcms/commerce-stripe#213]
### Description
Whenever I submit the payment form I get an error saying "Payment Method Id cannot be blank." I followed your guide on the README.

Here is my code:

` <section class="container-sm">
    <div class="row">

      <div class="flex flex-col-reverse lg:flex-row justify-between">
        <div class="w-full lg:w-6/12  mt-8 lg:mt-0">
          {% set cart = craft.commerce.carts.cart %}

          {% set paymentSources = craft.commerce.paymentSources.allPaymentSourcesByUserId(currentUser.id ?? null) %}

          {# Get the available gateways to be used later in this page #}
          {% set availableGateways = craft.commerce.gateways.allCustomerEnabledGateways %}

          {# If there are no gateway then payment sources wont work either, so lets #}
          {% if availableGateways is empty %}
            <p>No payment methods available.</p>
          {% endif %}

          {% set gateway = craft.commerce.gateways.getGatewayById('2') %}
          {% set redirectUrl = '/shop/checkout/order/' ~ cart.number %}
          <div>
            <h2 class="text-black font-sans font-light text-16 mb-8">Payment</h2>
            <form method="post" action="" class="js-paymentSource-form" id="payment-form">
              {{ actionInput('commerce/payments/pay') }}
              {{ redirectInput('/shop/checkout/order/' ~ cart.number) }}
              {{ hiddenInput('cancelUrl', '/commerce/checkout/payment/cancel'|hash) }}
              {{ hiddenInput('gatewayId', gateway.id) }}
              {{ csrfInput() }}
              <input type="hidden" name="orderEmail" value="{{ cart.email }}"/>
              <input type="hidden" name="orderNumber" value="{{ cart.number }}"/>

              {% set billingAddress = cart.billingAddress ?? null %}
              <fieldset class="mb-6">
                <div class="flex flex-col lg:flex-row lg:flex-no-wrap">
                  <div class="flex flex-col w-full mb-4 lg:mb-0 lg:w-1/2 lg:pr-4 ">
                    <label for="firstNameStripe" class="font-sans font-bold caption uppercase mb-2">{{'First Name'|t('commerce')}}</label>
                    <input type="text" id="firstNameStripe" name="firstName" maxlength="70" placeholder="" autocomplete="firstname" class="py-[11px] pl-[20px] font-sans font-light body-md text-black placeholder-grey-mid border border-field-grey border-solid w-full mt-4 card-holder-first-name{{(paymentForm is defined and paymentForm.getErrors('firstName') ? ' error')}}" value="{{paymentForm is defined and paymentForm ? paymentForm.firstName : ''}}" style="border-color:#D9D9D9;">
                  </div>
                  <div class="flex flex-col w-full mb-4 lg:mb-0 lg:w-1/2 lg:pl-4">
                    <label for="lastNameStripe" class="font-sans font-bold caption uppercase mb-2">{{'Last Name'|t('commerce')}}</label>
                    <input type="text" id="lastNameStripe" name="lastName" maxlength="70" placeholder="" autocomplete="lastname" class="py-[11px] pl-[20px] font-sans font-light body-md text-black placeholder-grey-mid border border-field-grey border-solid w-full mt-4 card-holder-last-name{{ (paymentForm is defined and paymentForm.getErrors('lastName') ? ' error') }}" value="{{paymentForm is defined and paymentForm ? paymentForm.lastName : ''}}" style="border-color:#D9D9D9;">

                  </div>
                </div>
              </fieldset>

              <fieldset class="mb-6">
                <div class="flex lg:flex-no-wrap">
                  <div class="flex flex-col w-full">
                    <label class="font-sans font-bold caption uppercase mb-2">{{'Card Number'|t('commerce')}}</label>
                    <div class="py-[11px] pl-[20px] font-sans font-light body-md text-black placeholder-grey-mid border border-field-grey border-solid w-full mt-4">
                      <div id="card-number"></div>
                    </div>
                  </div>
                </div>
              </fieldset>

              <fieldset class="mb-6">
                <div class="flex lg:flex-no-wrap -mx-4">
                  <div class="w-1/2 flex flex-col px-4">
                    <label class="font-sans font-bold caption uppercase mb-2">{{'Expiry date'|t('commerce')}}</label>
                    <div class="py-[11px] pl-[20px] font-sans font-light body-md text-black placeholder-grey-mid border border-field-grey border-solid w-full mt-4">
                      <div id="card-expiry"></div>
                    </div>
                  </div>
                  <div class="w-1/2 flex flex-col px-4">
                    <label class="font-sans font-bold caption uppercase mb-4">{{'CVV'|t('commerce')}}</label>
                    <div class="py-[11px] pl-[20px] font-sans font-light body-md text-black placeholder-grey-mid border border-field-grey border-solid w-full">
                      <div id="card-cvc"></div>
                    </div>
                  </div>
                </div>
              </fieldset>

              {% set errors = paymentForm is defined and paymentForm ? paymentForm.getErrors() : [] %}
              {% if errors|length %}
                <ul class="errors">
                  {% for error in errors %}
                    <li>{{ error|join('<br>')|raw }}</li>
                  {% endfor %}
                </ul>
              {% endif %}

              <div id="card-errors" role="alert"></div>

              <button class="mt-6 mb-4 bg-black text-white font-san font-light text-16 px-8 py-4 flex flex-row justify-center items-center border-2 border-black hover:bg-transparent hover:text-black  disabled:bg-grey-min disabled:cursor-not-allowed disabled:text-black-light" type="submit">
                Pay securely
                <svg width="16" height="10" class="ml-2" viewBox="0 0 16 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" class="fill-current" clip-rule="evenodd" d="M3 5C3 4.5399 3.37298 4.16692 3.83308 4.16692H12.1108L9.66765 1.77725C9.32977 1.44676 9.33019 0.902905 9.66859 0.572933C9.99547 0.254194 10.5169 0.254174 10.8438 0.572889L15.3846 5L10.8438 9.42711C10.5169 9.74583 9.99547 9.74581 9.66859 9.42707C9.33019 9.0971 9.32977 8.55324 9.66765 8.22275L12.1108 5.83308H3.83308C3.37298 5.83308 3 5.4601 3 5Z" fill="#838383"/>
                </svg>
              </button>

            </form>
            <div class="flex flex-col justify-center py-8">
              {% include "partials/components/checkout/_card-providers" only %}
            </div>
          </div>

        </div>
        <div class="w-full lg:w-4/12">
          {% if cart.lineItems %}
            {% include "partials/components/checkout/_total" only %}
          {% endif %}
        </div>
      </div>

    </div>

  </section>
{% do view.registerJsFile('https://js.stripe.com/v3/') %}
{% js %}
    var stripe = Stripe('{{ parseEnv(gateway.publishableKey) }}');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
    base: {
    color: '#000000',
    fontSize: '16px',
    '::placeholder': {
    color: '#CCCCCC'
    }
    },
    invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
    }
    };

    var classes = {
    base: 'StripeElement',
    complete: 'StripeElement--complete',
    empty: 'StripeElement--empty',
    focus: 'StripeElement--focus',
    invalid: 'StripeElement--invalid',
    webkitAutoFill: 'StripeElement--webkit-autofill'
    };

    var card = elements.create('cardNumber', {
    style: style,
    classes: classes
    });
    card.mount('#card-number');

    var expiry = elements.create('cardExpiry', {
    style: style,
    classes: classes
    });
    expiry.mount('#card-expiry');

    var cvc = elements.create('cardCvc', {
    style: style,
    classes: classes
    });
    cvc.mount('#card-cvc');

    // Handle real-time validation errors from the card Element.
    function cardErrors(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
    displayError.textContent = event.error.message;
    } else {
    displayError.textContent = '';
    }
    };

    card.addEventListener('change', cardErrors);
    expiry.addEventListener('change', cardErrors);
    cvc.addEventListener('change', cardErrors);

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    event.preventDefault();
    var firstName = document.querySelector('.card-holder-first-name');
    var lastName = document.querySelector('.card-holder-last-name');

    var paymentData = {
    billing_details: {
    name: firstName.value + ' ' + lastName.value,
    email: '{{ cart.email }}',
    address: {
    line1: '{{ billingAddress.addressLine1 ?? '' }}',
    city: '{{ billingAddress.locality ?? '' }}',
    state: '{{ billingAddress.locality ?? '' }}',
    postal_code: '{{ billingAddress.postalCode ?? '' }}',
    country: '{{ billingAddress.countryCode ?? '' }}'
    }
    }
    };

    stripe.createPaymentMethod('card', card, paymentData).then(function(result) {
    if (result.error) {
    // Show the user any errors
    var errorElement = document.getElementById('card-errors');
    errorElement.textContent = result.error.message;
    } else {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'paymentMethodId'); // Craft Commerce only needs this
    hiddenInput.setAttribute('value', result.paymentMethod.id);
    form.appendChild(hiddenInput);

    form.submit();
    }
    });
    });

  {% endjs %}
`

Any solutions here?

### Additional info

- Craft CMS version: 4.1.4
- Stripe for Craft Commerce version: 3.0.1

**Comment by atelieridc** [comment]
Same issue:
- Craft CMS Pro 4.2.0.1
- Craft Commerce PRO 4.1.0
- Stripe for Craft Commerce 3.0.1

Clean setup of the Stripe for Craft Commerce. All templates have been checked and the Stripe Keys are correct (test mode)

Yii Debug Tool > requests > parameters:
'action' => 'commerce/payments/pay'
    'redirect' => '7de704ae79dafea4539dba5fae42b0e2476e8ac95101f5df1d07d1bc70b1e811https://test-site.ddev.site:8443/shop/checkout/order-confirmation?number=5c7b900b16fca5edc20afb301d064f43&success=true'
    'cancelUrl' => 'e4c7231e9b5a0ceb5d41dd6452205412126499871d0881d527ca8e064eaf12ddhttps://test-site.ddev.site:8443/shop/checkout/payment'
    'gatewayId' => '2'
    'orderEmail' => 'email@site.com'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••'
    'accept-terms' => 'on'
    'firstName' => 'FIRSTNAME'
    'lastName' => 'LASTNAME'
    'paymentMethodId' => 'pm_1LQYCMBrPbSFOQ6o99VI3vYp'

Yii Debug Tool > requests > session:
xxxxxx__flash: 'error' => 1
error: 'Invalid payment or order. Please review.'

**Comment by hassanmah** [comment]
@atelieridc I get exactly the same, I noticed that the 'paymentMethodId' actually gets returned and the the code below does actually adds the hidden input with the paymentMethodId to the form but still get an error

`stripe.createPaymentMethod(paymentData).then(function(result) {
    if (result.error) {
    // Show the user any errors
    var errorElement = document.getElementById('card-errors');
    errorElement.textContent = result.error.message;
    } else {
    // Insert the token ID into the form so it gets submitted to the server
    console.log('here' + result.paymentMethod.id)
    var form = document.querySelector('.js-paymentSource-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'paymentMethodId');
    hiddenInput.setAttribute('value', result.paymentMethod.id);
    form.appendChild(hiddenInput);
    form.submit();
    }
    });`

**Comment by tomjrjones** [comment]
Any update on this ? Im experiencing the same issue @hassanmah @atelieridc

**Comment by hassanmah** [comment]
@tomjrjones Sorry not managed to figure out the issue

**Comment by hassanmah** [comment]
Fixed this, so input name for 'paymentMethodId' updated to 'paymentForm[stripe][paymentMethodId]'

I think the 'stripe' bit is the gateway name

**Comment by tomjrjones** [comment]
@hassanmah Struggling to get this working any chance I can get a copy of your template?

**Comment by tomjrjones** [comment]
@hassanmah Managed to get passed the payment Id error, but now Im getting 

    'error' => 'No such customer: \'xxx\'; a similar object exists in live mode, but a test mode key was used to make this request.'

Have you had any of the same issues ?

Thanks,
Tom

**Comment by tomjrjones** [comment]
Apologies for the spam managed to get past that error, using https://github.com/craftcms/commerce-stripe/issues/62

I nuked the stripe_customers table and it works now.

Just an FYI for anyone else struggling with this.

**Comment by curtismorte** [comment]
To add to what @hassanmah said, the solution here is for the Javascript specifically. In the docs they state:
```javascript
var form = document.getElementById('payment-form');

form.addEventListener('submit', function(event) {
    event.preventDefault();

    var paymentData = {
        billing_details: {
            email: "{{ cart.email }}",
        }
    };

    stripe.createPaymentMethod('card', card, paymentData).then(function(result) {
        if (result.error) {
            // Show the user any errors
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
        } else {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'paymentMethodId'); // Craft Commerce only needs this
            hiddenInput.setAttribute('value', result.paymentMethod.id);
            form.appendChild(hiddenInput);

            form.submit();
        }
    });
});
```
> You need to change the name attribute to have a value that uses `paymentForm[{GATEWAY_HANDLE}][paymentMethodId]`

So your Javascript would need to be:
```javascript
var form = document.getElementById('payment-form');

form.addEventListener('submit', function(event) {
    event.preventDefault();

    var paymentData = {
        billing_details: {
            email: "{{ cart.email }}",
        }
    };

    stripe.createPaymentMethod('card', card, paymentData).then(function(result) {
        if (result.error) {
            // Show the user any errors
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
        } else {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'paymentForm[{GATEWAY_HANDLE}][paymentMethodId]'); // Craft Commerce only needs this
            hiddenInput.setAttribute('value', result.paymentMethod.id);
            form.appendChild(hiddenInput);

            form.submit();
        }
    });
});
```
