### ISSUE TITLE
Missing Client Secret, possibly related to "Payment Method Id cannot be blank."

### ISSUE THREAD

**Issue by tomjrjones** [craftcms/commerce-stripe#214]
In the Readme it states in the javascript section once you have produced a stripe object you need to create an instance of the stripe elements:

`var elements = stripe.elements();`

But in the stripe documentation it states

`var elements = stripe.elements({
  clientSecret: 'CLIENT_SECRET',
});`

How are you handling the client secret or is this something that we are missing, as currently I get a "Payment Method Id cannot be blank." error. I was wondering if the missing client secret is related to this error ? I am aware there is already an issue open for the payment error.

https://github.com/craftcms/commerce-stripe/issues/213

Keep up the good work at Pixel & Tonic

Cheers,
Tom

### Additional info

- Craft CMS version: 4.2.01
- Craft Commerce version: 4.1.0
- Stripe for Craft Commerce version: 3.0.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by pixelmachine** [comment]
@tomjrjones I see you solved the issue but did you manage to get the clientSecret or just go with the old setup?

**Comment by westhouseit** [comment]
@tomjrjones any update on the question by @pixelmachine?
