### ISSUE TITLE
Apple Pay with Stripe plugin not supported?

### ISSUE THREAD

**Issue by philipboomy** [craftcms/commerce-stripe#222]
### Description

I am trying to get Apple Pay working but when I pass in the token I get from Stripe to commerce/payments/pay I am getting this error:

**A token may not be passed in as a PaymentMethod. Instead, use payment_method_data with type=card and card[token]=tok_xxxxxxxxxLIVKdQECvF.**

I am wondering if the Commerce Stripe plugin is supporting Apple Pay?

A quick search shows this: https://stackoverflow.com/questions/72043013/a-token-may-not-be-passed-in-as-a-paymentmethod-instead-use-payment-method-da

### Additional info

- Craft CMS version: 4.3.1
- Stripe for Craft Commerce version: 3.0.1

**Comment by pdaleramirez** [comment]
@philipboomy Commerce stripe plugin only supports credit card payments for now. We have plan to add more payment integration but can't give a specific timeline.

**Comment by andykearney** [comment]
+1

**Comment by ryssbowh** [comment]
This is a problem for us too.
I managed to integrate Google pay with some custom code but that last bit I can't get over.
The key `payment_method` is hardcoded there https://github.com/craftcms/commerce-stripe/blob/develop/src/gateways/PaymentIntents.php#L498 and we can't change it.
Until google pay is supported can you add an event to modify the `requestData` before it's sent to Stripe ?

**Comment by ryssbowh** [comment]
For others that may need this, I managed to get this working by cloning the plugin and replacing this line 498 by :
```
if (substr($paymentMethodId, 0, 4) == 'tok_') {
    $requestData['payment_method_data'] = [
        'type' => 'card',
        'card' => [
            'token' => $paymentMethodId
        ]
    ];
} else {
    $requestData['payment_method'] = $paymentMethodId;
}
```

**Comment by moldedjelly** [comment]
We've been wanting this too. 
It would be great if the plugin was upgraded to support the newer Payment Element approach

**Comment by pxel** [comment]
+1 eager to have this also.

**Comment by sparkalow** [comment]
+1  
We had to go with WP for apply pay due to timing and I hated every minute of it.

**Comment by lukeholder** [comment]
Good news! See our announcement:

 https://craftcms.com/blog/commerce-4-3-stripe-4

**Comment by pxel** [comment]
👏 Awesome news
