### ISSUE TITLE
Denied 3d secure is emptying cart upon returning to payment page

### ISSUE THREAD

**Issue by john-henry** [craftcms/commerce-stripe#229]
### Description
On live and test Stripe using 3d secure when a card is denied it redirects back to payment page on client's site but it also empties the cart. I'm guessing that is not intended behaviour? How do you suggest troubleshooting this?

### Additional info

- Craft CMS version:3.7.65.2
- Stripe for Craft Commerce version:^2.4 & 3.4.19
- PHP version:8.0
- Database driver & version:
- Plugins & versions:

**Comment by pdaleramirez** [comment]
@john-henry I can’t seem to reproduce this issue. Can you send us your database and composer.json files to support@craftcms.com? We’ll debug further.

**Comment by lukeholder** [comment]
Please re-open a new issue with steps to reproduce and we can take a look at this again. Marking this as stale. Thanks.
