### ISSUE TITLE
stripe form loses focus if a password field exists and hidePostalCode: false

### ISSUE THREAD

**Issue by okay-type** [craftcms/commerce-stripe#243]
### Description

The stripe card element loses focus after entering six digits in the credit card field if:
- there is a <input type='password'> on the page
- the "hidePostalCode" setting is false (six digits seems to be when that field pops up in the card element)
- you use a test number like "4242424242424242" or similar (other numbers work)

### Steps to reproduce

1. Add an <input type='password'> 
2. Set hidePostalCode: false in the elements.create('card' options
3. Reload and try to type in the credit card number "4242424242424242". After six digits, the form focus changes to the first input on the page.

### Additional info

- Craft CMS version: Craft Pro 4.4.15
- Stripe for Craft Commerce version: 3.1.1
- PHP version: 8.0.28
- Database driver & version: MariaDB 10.4.28
- Plugins & versions: 
AsyncQueue	3.1.0
Control Panel JS	2.6.0
Control Panel Nav	4.0.10
Craft Commerce	4.2.11
Enupal Snapshot	2.0.1
Environment Label	4.0.3
Mailgun	3.0.0
Minify	4.0.0-beta.2
Patrol	5.0.2
Plausible	2.1.0
Stripe for Craft Commerce	3.1.1
Super Table	3.0.9

**Comment by lukeholder** [comment]
Good news! We are now using the new Stripe elements form with better validation. See our announcement:

 https://craftcms.com/blog/commerce-4-3-stripe-4
