### ISSUE TITLE
3D secure is redirecting back to home page

### ISSUE THREAD

**Issue by kevadamson** [craftcms/commerce-stripe#245]
### Description

I'm using Stripe Payment Intents

`{{ redirectInput(siteUrl ~ '' ~ entry.uri ~ '?payment=success#buy') }}`
`{{ cart.getGateway().getPaymentFormHtml({})|raw }}`

I test using the following card:

`4000000000003220` (3DS2)

It takes me to the test 3DS page, when I click authorise it takes me to my website root home page, rather than the redirect URL above. Redirect URL works when no 3DS used (for e.g. `4242424242424242`).

I'm testing on a development server with no password set for access.

### Additional info

- Craft CMS version: Craft Pro 3.8.17
- Stripe for Craft Commerce version: 2.4.4.1
- PHP version: 8.1.4
- Database driver & version: MySQL 8.0.27

**Comment by AugustMiller** [comment]
Hey Kev, sorry for the delay!

Can you try providing a `cancelUrl` param in your request, as well? The `commerce/payments/pay` action requires that these are _both_ set to handle a return from an offsite payment process.

**Comment by peterurban** [comment]
+1

Adding a cancelUrl didn't solve the problem.

**Comment by lukeholder** [comment]
@peterurban are you using the new payment intent for in 4.1.x - this should fix the issue for you. Make sure to look at the example templates to see how it works. Thanks.
