### ISSUE TITLE
Gateway javascript conflicts with jQuery when not written in no conflict mode

### ISSUE THREAD

**Issue by amphibian** [craftcms/commerce-stripe#249]
### Description

When Stripe Commerce loads its default javascript, it creates a conflict with jQuery if existing jQuery code has not been assigned to something other than `$`.

### Steps to reproduce

Load jQuery in the footer of a payment page and write some jQuery inside of a `document.ready` statement using the default `$` variable for jQuery. Then load the default gateway HTML for the Stripe Commerce plugin.

### Additional info

- Craft CMS version: 4.5.5
- Stripe for Craft Commerce version: 4.0.0
- PHP version: 8.1.13
- Database driver & version: MySQL 5.7.39

**Comment by lukeholder** [comment]
FIxed in 4.0.1
