### ISSUE TITLE
Could you please enable the different payment methos from stripe

### ISSUE THREAD

**Issue by nordentwickler** [craftcms/commerce-stripe#25]
Stripe offers more payment methods like giropay and sofort. There should be a possibility to enable those methods in the gateway-section of the commerce-stripe plugin as well.

Stripe is more than just cards :D

@lukeholder as i ask in the workshop

**Comment by andris-sevcenko** [comment]
@nordentwickler  When offering giropay and sofort in your site, would those be distinct payment methods? For example, would a site offer the user a choice of giropay, sofort or card?

**Comment by andris-sevcenko** [comment]
Closing this, splitting it out to #26 and #27
