### ISSUE TITLE
Adding a payment source works but results in error 404

### ISSUE THREAD

**Issue by mc-tomjrjones** [craftcms/commerce-stripe#259]
I am currently on Commerce Stripe version 4.0.1 and Craft Commerce 4.3.0. 

When adding a payment method it redirects to 
...index.php/actions/commerce-stripe/customers/confirm-setup-intent&CRAFT_CSRF_TOKEN=...&redirect_status=succeeded.

This results in a error 404 but it has in fact added the payment source. All the events in the stripe webhook have succeeded so not entirely sure why it is not returning me to my form's redirectInput value.

Any idea where to go from here?

Many Thanks,
Tom

**Comment by peterurban** [comment]
Any update on this?

I am having the exact same issue. Seems there might be a problem with the url params starting with & instead of ?.

This is really critical as it prevents us from accepting any subscriptions...

**Comment by lukeholder** [comment]
Please add comments to https://github.com/craftcms/commerce-stripe/issues/289

We can't seem to reproduce. Any addition info on that ticket would be helpful.
