### ISSUE TITLE
Missing icon-mask.svg

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce-stripe#260]
### Description

I've noticed that my log is filling up with these errors:

Category
`craft\controllers\UtilitiesController::_getUtilityIconSvg`

Message
`Utility icon file doesn't exist: /home/*/*/releases/*/craft/vendor/craftcms/stripe/src/icon-mask.svg`

Possibly due to this line: https://github.com/craftcms/commerce-stripe/blob/b10503188c4c64efe3f20baf300a669cfbcac16e/src/utilities/Sync.php#L44

Path should be `/craftcms/commerce-stripe/src/icon-mask.svg`

### Additional info

- Craft CMS version: 4.5.9
- Stripe for Craft Commerce version: 4.0.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @jonleverrier 

Great spot! Have pushed up a fix for this which will be included in the next release of the plugin.

To get this early, change your `craftcms/commerce-stripe` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce-stripe": "dev-develop#d72340afb66fda8bbe5801a6adb57ab5596728d5 as 4.0.1",
  "...": "..."
}
```

Then run `composer update`.

Thanks!
