### ISSUE TITLE
Checkout Payment Form Not Displayed

### ISSUE THREAD

**Issue by yumpdevs** [craftcms/commerce-stripe#267]
### Description
When using Stripe API Key with default version `2017-02-14` in `Commerce 4` and `Stripe for Craft Commerce 4.0.1.1`, the checkout payment form is not display, and no error generated in craft log and stripe log, except `<div class="stripe-error-message">undefined</div>` in frontend. 

And the `public const STRIPE_API_VERSION = '2022-11-15';` which at line 134 in file gateway.php, used in function `getStripeClient()` at line 177 in file gateway.php is not work. The Stripe log for the failed transaction still indicates the failed transaction is at the version` 2017-02-14` (The transaction failed with `"status": "requires_source"` because the payment form is not displayed and no place to enter the card information).

Is there a way to add the customize stripe version in the plugin settings to the Stripe Headers before sending Stripe Request? It is not very realistic for me to upgrade the Stripe API default version since multiple transaction activities are linked to it.

Have tried using Stripe key under another accounts with version 2020-08-27 and 2023-10-16 in the same project, works fine and this issue not occur, so it is not the code issue.

### Additional info

- Craft CMS version: 4.5.11
- Stripe for Craft Commerce version: 4.0.1.1
- PHP version: 8.1

**Comment by DanielDarrenJones** [comment]
@lukeholder We are having a similar issue - we can't update the default as there are multiple other applications using older API versions, as @yumpdevs mentioned it looks like the API version is hardcoded in the gateway.php file to '2022-11-15', but this doesn't seem to be making its way into the request.

Is there a reason the hardcoded API version isn't working here from the codebase?
