### ISSUE TITLE
[4.0.1.1] Cannot access handlerInstance

### ISSUE THREAD

**Issue by okolvik-avento** [craftcms/commerce-stripe#275]
The handler instance cannot be saved in the element dataset. Which means that it's impossible to update the stripe element after initialization. (For example to toggle darkmode)

This is probably a holdover from the old jQuery code.

This either needs to be updated by a global in window, or even better a customevent with the instance in details.

https://github.com/craftcms/commerce-stripe/blob/1d0010b24cf89282f405057b82f60753becabfdc/src/web/assets/elementsform/js/paymentForm.js#L301C7-L301C7

**Comment by nfourtythree** [comment]
Hi @okolvik-avento 

Thank you for reporting this. We have pushed up a [fix for this](https://github.com/craftcms/commerce-stripe/pull/283) which we hope to merge in shortly and subsequently put out a release of the Stripe plugin.

The fix will allow you to do the following:

```js
document.querySelector('.stripe-payment-elements-form').handlerInstance.elements.update({
  appearance: {theme: 'stripe'}
});
```

Thanks!

**Comment by nfourtythree** [comment]
hi @okolvik-avento 

Version `4.1.1` of the plugin has now been released with this update included.

Thanks!
