### ISSUE TITLE
Refactor Stripe gateway

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce-stripe#28]
Current Strip gateway should be refactored, splitting out the common functionality to a base gateway, to reduce code duplication when implementing #26 and #27 

Related: #25

**Comment by stenvdb** [comment]
Hi @andris-sevcenko what is the progress on this issue? I'm wondering if we can expect different gateway types soon for Stripe. I'm myself interested in seeing Bankcontact supported.

**Comment by andris-sevcenko** [comment]
We're working on EU SCA support for Stripe. For the change to be backward compatible, this requires a new gateway, so this is happening now.

As far as Bankcontact support goes - can you add a new issue for this?
