### ISSUE TITLE
Stripe package conflict

### ISSUE THREAD

**Issue by paulmendrik** [craftcms/commerce-stripe#287]
### Description

When trying to update the plugin  get the following message even though there don't appear to be any other using this.

Problem 1
    - craftcms/commerce-stripe 4.1.1 requires stripe/stripe-php ^10.0 -> found stripe/stripe-php[v10.0.0, ..., v10.21.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires craftcms/commerce-stripe 4.1.1 -> satisfiable by craftcms/commerce-stripe[4.1.1].

### Additional info

- Craft CMS version: 4.6.1
- Craft Commerce: 4.4.1.1
- Stripe for Craft Commerce version: 3.1.1
- PHP version: 8.2.4
- Database driver & version:
- Plugins & versions:
- ImageOptimize: 4.0.5
- Redactor: 3.0.4
- Super Table: 3.0.12
- Store Hours: 3.0.0

**Comment by lukeholder** [comment]
try `composer why stripe/stripe-php` to see what is currently requiring the stripe package. It is likely you have another plugin requiring Stripe which is conflicting.
