### ISSUE TITLE
yii\base\ErrorException: Undefined array key "billing"

### ISSUE THREAD

**Issue by Saboteur777** [craftcms/commerce-stripe#294]
### Description

When a Stripe webhook is sent, I get this error message. 

### Steps to reproduce

1. Set up Stripe payment gateway as usual. 
2. Enable these events for the webhook:
```
payment_method.updated
payment_method.automatically_updated
payment_method.detached
plan.updated
plan.deleted
customer.subscription.updated
customer.subscription.deleted
invoice.payment_succeeded
invoice.payment_failed
invoice.created
```
3. Check the logs after an invoice has been created. 

### Additional info

- Craft CMS version: Craft Pro 3.9.12
- Stripe for Craft Commerce version: 2.4.4.1 *
- PHP version: 8.1.27
- Database driver & version: MariaDB 11.3.2
- Stripe API version: 2020-08-27

* This part of the code is unchanged, should still be present in current versions.

**Comment by nfourtythree** [comment]
Hi @Saboteur777 

Thank you for bringing this to our attention, we have created a fix for the issue and published the following versions of the Stripe plugin:

- `5.0.1`
- `4.1.2.2`
- `3.1.2`
- `2.4.5`

Thanks!

**Comment by Saboteur777** [comment]
Thank you, Nathaniel! It's awesome that you backported it to older versions. 👏

Just out of curiosity: why did you go with 

```
$stripeInvoiceBilling = isset($stripeInvoice['billing']) && $stripeInvoice['billing'] ? $stripeInvoice['billing'] : null;
```

instead of using the null coalescing operator?

**Comment by nfourtythree** [comment]
No problem @Saboteur777 

As for the code, just for a little bit more verbosity and creates a bit of self-documenting code. 

Yes, null coalescing is shorter/tidier but it doesn't really tell the story as to why, as it captures both if the value is `null` but also if the key doesn't exist.

In the future, it will be more obvious if there is a possibility to remove this code if Stripe is no longer passing the key for example.

Could have certainly gone with either method.

Thanks!

**Comment by Saboteur777** [comment]
Thanks for the explanation – it is always interesting to understand how other developers decides which solution to use and why.
