### ISSUE TITLE
checkoutSuccessUrl doesn't work.

### ISSUE THREAD

**Issue by dbrown199747** [craftcms/commerce-stripe#300]
### Description
checkoutSuccessUrl doesn't work.

I have added the checkout success URL to the optiont in twig, the 'Success Return URL' field in the pro setting tab, and also in the 'Checkout Success URL' field in the payment form page. However none of these work and once the payment is made, it just redirects back to the root domain name. Do you have nay idea what i'm doing wrong?

Screenshots attached below:

![Screenshot 2024-04-27 at 12 15 34](https://github.com/craftcms/commerce-stripe/assets/83223160/478d0457-43e5-4b2e-8cf9-dbee6d60141d)

<img width="990" alt="Screenshot 2024-04-27 at 12 15 47" src="https://github.com/craftcms/commerce-stripe/assets/83223160/2187c92c-4d08-4359-887c-4a3785dd2f75">

<img width="369" alt="Screenshot 2024-04-27 at 12 15 27" src="https://github.com/craftcms/commerce-stripe/assets/83223160/ab1eaeb8-303b-497c-8127-db4846aa04ed">

### Additional info

- Craft CMS version: Craft Pro 4.8.8
- Stripe for Craft Commerce version: 5.5.2
- PHP version: 8.0.30
- Database driver & version: MySQL 5.7.44
- Plugins & versions:
Agent: 5.0.0
Formie: 2.1.10
HOMM XML Sitemap: 1.0.3
Porter: 1.0.4
Redactor: 3.0.4
Super table: 3.0.13
Typed link field: 2.1.5

**Comment by lukeholder** [comment]
I think this bug report is for the Enupal Stripe plugin? Is that correct? This is the Commerce Stripe plugin repo for Craft Commerce.
