### ISSUE TITLE
[4.x]: "Make a payment" on manual gateway order doesn't work

### ISSUE THREAD

**Issue by AmandaLutzTO** [craftcms/commerce-stripe#303]
### Description

Commerce > System Settings > Gateways includes Dummy, Stripe Payment Intents (for credit card), and Manual (for check and purchase order). A check/purchase order order is successfully created but in the backend, Order > Transactions > Make a payment shows `Calling unknown method: craft\commerce\stripe\gateways\PaymentIntents::getOldPaymentFormHtml()`

### Steps to reproduce

1. create new ecom order
2. select payment method of type Manual (ie Check or Purchase Order)
3. order is successfully completed
4. go to Craft backend
5. find the unpaid order and click to edit
6. go to the Transactions tab
7. click "Make a payment" button

### Expected behavior

Enter payment amount and order's Paid Status changes from Unpaid.

### Actual behavior

Modal window with message `Calling unknown method: craft\commerce\stripe\gateways\PaymentIntents::getOldPaymentFormHtml()` 
![image](https://github.com/craftcms/commerce/assets/4438820/2543c84a-593f-42df-9a79-4dc20839c8c9)

### Craft CMS version

4.7.1

### Craft Commerce version

4.5.3

### PHP version

8.1.8

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.32

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Stripe for Craft Commerce (3.1.1)

**Comment by AmandaLutzTO** [comment]
I just noticed. Why is it calling a Stripe gateway function? Yes, we have Stripe for Craft Commerce (3.1.1) installed but this order shouldn't be referring to it.

**Comment by AmandaLutzTO** [comment]
I have just tried another order with a brand new test user that has no cc info associated with it. Same result.

**Comment by lukeholder** [comment]
@AmandaLutzTO I have just pushed commerce-stripe 3.1.3, which fixes this issue. Thanks!
