### ISSUE TITLE
Pass parameters to stripe for subscription

### ISSUE THREAD

**Issue by johnnyhawley** [craftcms/commerce-stripe#31]
Is there a way to pass parameters to stripe when creating a subscription? I need to programmatically set the trial_end parameter as well as the billing_cycle_anchor parameter and not pass in the trial_days parameter to stripe.

I was hoping to use the EVENT_BUILD_GATEWAY_REQUEST hook, but that seems to only be triggered with orders.

**Comment by andris-sevcenko** [comment]
Not at the moment, but shouldn't be hard to do. I'll add it to the list and hope to do that on Monday for you.
