### ISSUE TITLE
Payment form page auto-completes orders with $0 subtotal

### ISSUE THREAD

**Issue by benjaminkohl** [craftcms/commerce-stripe#313]
### Description

We are experiencing an issue where discount code applied orders with a subtotal of $0 are auto-completing at some point _after_ the payment form page loads. Rather than Stripe loading the payment method fields and "complete" button like usual, nothing loads in that spot and the order gets completed behind the scenes. The user is left on that page with no actions to perform and it is causing confusion. Meanwhile, the order notification email is sent to the user and the order appears in the control panel as completed with a Status of "Processing" and a Paid Status of "Paid".

The client is fine with the user being able to skip the payment portion for these orders since it isn't necessary, but what I don't understand is how to appropriately redirect the user to the order confirmation page upon completion and I can't find any documentation explaining to me exactly what's occurring and when it is occurring or how to handle it appropriately.

### Steps to reproduce

1. Add product to cart and view cart.
2. Apply a discount code that reduces the order total to $0.
3. User gets redirected to a page where they select their billing address (or add a new one).
4. User gets redirected to payment form page where Stripe does not load the payment fields but the order gets completed behind the scenes at some point after page load. This was determined by me checking the cart/order status during the page rendering and it was not yet returning `true` for `cart.isCompleted`.

![Image](https://github.com/user-attachments/assets/443ef651-0791-4738-b517-3ff2cf6f0713)

### Additional info

- Craft CMS version: 4.12.5
- Stripe for Craft Commerce version: 4.1.5
- Craft Commerce version: 4.6.13
- PHP version: 8.0.30
- Database driver & version: MariaDB 10.4.34
- Plugins & versions:

Amazon S3	2.2.1
Cache Flag	1.4.0
CP Field Inspect	1.4.4
Craft Commerce	4.6.13
Embedded Assets	4.1.2
Facebook Conversion	v1.3.3
Google Maps	4.5.2
Guest Entries	4.0.1
Imager X	4.4.1
Inventory	3.2.0
Lab Reports	2.0.3
Link Vault	4.0.4
Minify	4.0.1
PayPal Checkout for Craft Commerce	2.1.3
Preparse	2.1.2
reCAPTCHA	3.0.0
Redactor	3.1.0
Retour	4.1.19
SEOmatic	4.1.4
Stripe for Craft Commerce	4.1.5
Super Table	3.0.15

**Comment by lukeholder** [comment]
It looks like the issue was fixed in 5.0.4.3:

https://github.com/craftcms/commerce-stripe/blob/5.x/CHANGELOG.md#5043---2024-09-17

I see you are using a previous version of commerce. I went ahead an backported the fix to 4.x

You should be able to upgrade now to 4.1.5.1 to get the fix. It will auto-redirect to the confirmation page if the order is completed due it being a free order.

If you don't want it to be automatic (the redirect) when they land on the page, you should not output the stripe payment form if the order is free and instead submit to the pay controller without the payment form outputted.

**Comment by benjaminkohl** [comment]
Thank you! I installed this update and it works like a charm.
