### ISSUE TITLE
Allow setting `transfer_group` identifier

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce-stripe#33]
We're looking at implementing a kind of merchant system for event ticket sales, and would love to have a way of sending an initial [`transfer_group` param](https://stripe.com/docs/connect/charges-transfers#grouping-transactions) for Charges. Periodically, we're going to make Transfers to event organizers (carts may contain tickets from multiple organizers), and pairing these up will make record keeping much easier—and (in theory) tie them together in the Stripe dashboard.

I appreciate the decision to ignore modifications to the `Transaction` object when emitting the `EVENT_BUILD_GATEWAY_REQUEST`, but because this is a core param (and not a `metadata` candidate), we don't have a way of including this.

Is that something to be accomplished with a custom event? Probably not something to do by default, but emitting `EVENT_ASSIGN_TRANSFER_GROUP` would be super useful!

…or, maybe there's another way to tap in to the request params, already?

❤️

**Comment by AugustMiller** [comment]
Well, if I'd kept reading, it looks like [you might be able to retroactively group these](https://stripe.com/docs/connect/charges-transfers#transfer-availability), when creating Transfers in Stripe… I'll continue to investigate.

**Comment by andris-sevcenko** [comment]
What's your timeline for this?

**Comment by AugustMiller** [comment]
Nothin urgent. Still in the proposal phase for the project, and doing some research! If we find ourselves at an impasse, I'm happy to issue a PR—I imagine this is a pretty infrequent use-case, and it may already be handled by the Transfer API.

Will @ you if I find out anything actionable! :)

**Comment by andris-sevcenko** [comment]
The `EVENT_BUILD_GATEWAY_REQUEST` event allows for setting arbitrary parameters as of 04a1cdf334e98f86f17fd7c7934d9dac25614cc4

Sorry for the delayed notification :(
