### ISSUE TITLE
Refunded subscriptions are still accessible

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce-stripe#36]
When a subscription is refunded in Stripe, the subscription is still accessible on the Craft side.

Ideally it should make the subscription expired if the money is refunded, or have some settings to choose from in Commerce to set that if a refund is made, then the user can access the subscription for 0 Days, X Days after refund, at Subscription end etc.

**Comment by andris-sevcenko** [comment]
Refunding a subscription payment (one of many) and canceling a subscription are two different things. To accomplish this you want to refund the subscription payment and then expire the subscription manually on Stripe's dashboard.
