### ISSUE TITLE
Issue with subscription payments: "switched to a plan on Stripe that does not exist on this Site."

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce-stripe#46]
### Description

After an invoice has been paid within Stripe I'm seeing this error in Craft

`sub_DTlG04ToMTszpI was switched to a plan on Stripe that does not exist on this Site.`

For some context: about two months ago I needed to create new Subscriptions plans in Stripe, move current subscribers to that plan, and then reassign them inside Craft, and I'm assuming this has something to do with this.

However, the subscription Plan that's being used in Stripe, does match the plan the user is assigned to in the CMS, so I'm unsure how that connection is being missed? Here's a screenshot to show the consistent data. https://cl.ly/13c6bdfb0e6f 

I can also confirm the user is assigned to the right plan.

### Additional info

- Craft version: 3
- PHP version: 7/1
- Database driver & version: marina
- Plugins & versions: Commerce 2.0.0-beta.6

**Comment by andris-sevcenko** [comment]
This was due to earlier Stripe API versions using the plan handle as identifiers, which changed when they introduced products for subscriptions. A part of the gateway's code hadn't caught up with that particular change.

Thanks for the perseverance!
