### ISSUE TITLE
Webhook fails to find Subscription by reference

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce-stripe#47]
When receiving the `customer.subscription.deleted` event, the lookup by `reference` fails, as the subscription appears to have been expired, already… at least when using the `cancelImmediately` option.

```
2019-01-02 12:45:39 [-][-][-][warning][stripe] Subscription with the reference “sub_EGnwT4PvrrQoXK” not found when processing webhook evt_1DoGanIS4LqbsGJB6YDcCqyb
```

Trying the same resulting SQL with a non-expired subscription, or explicitly setting `isExpired: true` or `status: 'any'` will find the subscription just fine.

~What I don't understand though, is _how the subscription is marked as expired, before the webhook arrives_.~ Ah, found some evidence re: immediate cancellation that would suggest a subscription can be silently expired, outside the webhook loop.

This was uncovered as a result of a handler for `craft\commerce\services\Subscriptions::EVENT_AFTER_EXPIRE_SUBSCRIPTION` not firing—it seems as though the subscription _is_ being expired in the database, but the event never fires, because the webhook doesn't find the subscription, and bails…

Re: research, above… I'll submit another issue with `craftcms/commerce` with this info…

Sorry for the rambling! I may have partially resolved my own question/curiosity, but still believe there is a bug in how the webhook deals with “already-expired” subscriptions. My sense is that _the `EVENT_AFTER_EXPIRE_SUBSCRIPTION` event should always fire_, regardless of how the subscription is expired (immediately, or organically, at the period’s end).

**Comment by andris-sevcenko** [comment]
Fixed via https://github.com/craftcms/commerce-stripe/commit/d71dd172434a63b399d4bba89711738f8ad7baf5

**Comment by andris-sevcenko** [comment]
Thanks for the in-depth description!
