### ISSUE TITLE
Stripe not sending cart information when the option is turned on in settings.

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce-stripe#5]

**Comment by azazelA** [comment]
I don't know exactly what information it's supposed to send but I'm only getting the `Order # [32]`  in my stripe dashboard and not the full cart info.. that could include the cart items?

**Comment by andris-sevcenko** [comment]
Yeah, that setting won't work for Stripe and has been removed in the latest Commerce version.

If you want to add some more metadata to purchases, you should look into [using events](https://github.com/craftcms/commerce-stripe/blob/master/src/gateways/Gateway.php#L80-L100) for attaching more info to the request.
