### ISSUE TITLE
Potential information leak when using custom Invoices

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce-stripe#50]
Just encountered a really bizarre side effect of Invoices and Webhooks (I think)…

We were reviewing a couple of subscriptions in our system, and noticed a stray payment that didn't match any amount that would/could have been processed against the subscription.

It turns out that our client created an invoice for a donor via the Stripe dashboard, without any intent of having the payment be reflected in Craft.

Somehow (presumably in response to an `invoice.created` or `invoice.paid` webhook), that invoice was tied to what looks like the most recently-created Subscription, in Craft?

I'm not really sure what to make of it, or how to triage further… Our Stripe account confirms that there was only one payment made against the subscription.

We took a snapshot of our database, then trashed the record in `stripe_invoices` to avoid the subscriber finding an alarming invoice in their account.

---

I wonder if this doesn't have something to do with this lookup?
https://github.com/craftcms/commerce-stripe/blob/develop/src/gateways/Gateway.php#L1193

If there isn't a subscription reference on the Invoice, then… this would be `null`, right? Which means it'd blow out the scope of the query, and just grab the first subscription?

Any help would be appreciated! For the time being, we're halting any custom invoicing to avoid pollution of legitimate subscription histories.

**Comment by andris-sevcenko** [comment]
I was not possible to reproduce this. Following the same steps, I got an exception that a matching subscription could not be found. Closing this. If this happens again, please submit a new issue, as the codebase will have changed by then with the coming release of v2 of this plugin.
