### ISSUE TITLE
API Key Order Usability

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/commerce-stripe#52]
One of things I love about Craft is attention to detail...  in that vein, here's a minor usability thing.  

In the API settings, ``Publishable Key`` and ``Secret Key`` are listed in that order in the Stripe API Keys section:

![Screen Shot 2019-03-13 at 3 12 22 PM](https://user-images.githubusercontent.com/3707869/54311581-e164aa00-45a2-11e9-99fd-ff7c53f6b7d4.png)

In Commerce, the order of those keys are flip-flopped (ie ``Secret Key`` is listed first).

![Screen Shot 2019-03-13 at 3 12 16 PM](https://user-images.githubusercontent.com/3707869/54311608-f17c8980-45a2-11e9-9a96-e9ac57ee85a9.png)

It wouldn't be the first time I find myself second-guessing which key goes in which field as I copy and paste them from Stripe to Commerce.

I suppose that could be intentional but it would be better if they appeared in the same order, just for consistently (and sanity) sake.

**Comment by andris-sevcenko** [comment]
That makes sense to me.
