### ISSUE TITLE
3DS Flow: "Received unknown parameter: shipping"

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce-stripe#55]
So we recently added the "shipping" param to the requestData in our end and were met with this error `Received unknown parameter: shipping`. I've confirmed it's only with cards using the 3DS flow. For now, we've resolved this on our end by just removing the shipping parameter, but that's not an adequate long term solution for us.

Here is an example request being create via commerce-stripe:

```
{
  "amount": "14999",
  "currency": "USD",
  "metadata": {
    "order_id": "771430",
    "order_number": "bd126be6845dc9f317568ca157a3b171",
    "transaction_reference": "ad726d2679920d324735c14d8072d309",
    "client_ip": "192.168.10.1",
    "three_d_secure_flow": "true"
  },
  "shipping": {
    "address": {
      "city": "mumbai",
      "country": "India",
      "line1": "<redacted>",
      "line2": "",
      "postal_code": "65753",
      "state": ""
    },
    "name": "David Hahn"
  },
  "type": "three_d_secure",
  "three_d_secure": {
    "card": "src_1ENrmi2v7dE4TgLwSKdM5tCx"
  },
  "redirect": {
    "return_url": "<redacted>"
  }
}
```

and here is the response

```
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: shipping",
    "param": "shipping",
    "type": "invalid_request_error"
  }
}
```

One way I know this can be resolved is by the library checking if `type === 'three_d_secure'` and removing the `shipping`. The other way would be to offer another event right before it happens to allow developers to prune the data as they need. I can open a PR if that'd be helpful, but I wasn't sure which approach you think is best.

Versions:
PHP 7.3
Craft CMS: 3.1.21.1
Commerce: 2.1.3
commerce-stripe: 1.2.0

**Comment by andris-sevcenko** [comment]
@dhahn why did you close this one? It has a good point that the event handlers should be able to know what the request is for.

**Comment by dhahn** [comment]
Oops. I referenced it in our repo in a commit message 😊 Apparently Github connects across repos.

**Comment by andris-sevcenko** [comment]
@dhahn It does indeed. Guessing it's a private repo, otherwise I would have seen a link to the commit, too :)

**Comment by andris-sevcenko** [comment]
Because of how awkward it is, I'm going to close this one and go with "your plugin should check for that."

The reason behind this is we're almost done with v2 of this gateway, which will deprecate this API, anyway, so the actual recommendation at that point would be "You should switch to the Payment Intents gateway.", where 3DS will be handled in a synchronous manner.
