### ISSUE TITLE
Stripe Checkout / SCA

### ISSUE THREAD

**Issue by phillmorgan28** [craftcms/commerce-stripe#56]
Are there any plans to implement Stripe Checkout ahead of Sept to comply with EU SCA?

https://stripe.com/docs/strong-customer-authentication

**Comment by andris-sevcenko** [comment]
Stripe supports 3D Secure 1.0, which is compliant with SCA already.

Having said that, there are plans to support Stripe's Payment Intent API until September, which would ensure better customer experience when purchasing while also complying with SCA.

**Comment by phillmorgan28** [comment]
Unfortunately I would have to disagree. From the linked page:

> You will need to update your integration to support 3D Secure 2 before September 14, 2019. Integrations that are not SCA-ready, such as ones that use the Charges API, will start seeing high rates of declines on September 14, 2019.

A quick search shows that this plugin uses the Charges API.

**Comment by andris-sevcenko** [comment]
If the credit card entered either requires 3D Secure or (supports it and [the appropriate setting](https://github.com/craftcms/commerce-stripe#forcing-a-3d-secure-payment) is enabled), the plugin will switch to 3D Secure flow to create a payment source. To charge that source you have to use the Charges API, but that is not the same as simply using the Charges API. (https://stripe.com/docs/strong-customer-authentication/migration#d-secure-with-sources-api)

The 3D Secure Sources API is no longer recommended as that will not support 3D Secure 2, but, at the same time, there's no clarity on what's the support for 3D Secure 2 currently provided by banks. Also, there's no explicit mention of 3D Secure 1 not being SCA-ready.

Granted, I'm legalese guru, but it seems to me that 3DS1 does fulfill two of the "Knowledge", "Possession", and "Inherence" factors that are required to be SCA compliant.

**Comment by andris-sevcenko** [comment]
@phillmorgan28 just a heads up - after internal discussion, we've decided to move ahead with Payment Intents API immediately, just so that we're on the safe side and nobody starts to feel under stress about some impeding deadlines and whether it will work at all :)

**Comment by phillmorgan28** [comment]
Hi andris, thanks very much for getting back to me. That is excellent news! With Payment Intents looking to be the de facto standard for Stripe going forward, it's great to know you'll be supporting it soon. Thank you again.

**Comment by andris-sevcenko** [comment]
@phillmorgan28 We released Stripe v2 a few hours ago that has the Payment Intent gateway which supports 3D Secure 2.

**Comment by phillmorgan28** [comment]
Hi,

Using the latest plugin version, my initial tests show a compatibility issue with SCA when using the documented code available. Test card used was 4000 0000 0000 3220 which is documented as "3D Secure 2 authentication must be completed on all transactions. Use this card to test that your integration is ready to support Strong Customer Authentication requirements in Europe."

The response from Stripe was:

`{
    "error": {
        "charge": "ch_1F4OpRG6t8CScTBlMrpUwblS",
        "code": "authentication_required",
        "decline_code": "authentication_required",
        "message": "Your card was declined. This transaction requires authentication.",
        "type": "card_error"
    },
    "code": "authentication_required",
    "message": "Your card was declined. This transaction requires authentication.",
    "id": "ch_1F4OpRG6t8CScTBlMrpUwblS"
}`

I have followed the documentation here:
https://docs.craftcms.com/commerce/v2/making-payments.html

Payment form looks like this:

`<form method="POST" class="margin-top-md">
    <div class="well">
        <div class="well__section">
            <input type="hidden" name="action" value="commerce/payments/pay"/>
            {{ csrfInput() }}
                <div class="grid">
                    <div class="grid__item w-6-lg">
                        {{ redirectInput('/checkout/result?id=' ~ craft.commerce.carts.cart.number) }}
                        <input type="hidden" name="cancelUrl" value="{{ '/checkout'|hash }}"/>
                        {{ craft.commerce.carts.cart.gateway.getPaymentFormHtml({})|raw }}
                        </div>
                    </div>
                </div>
        </div>
    </div>
</form>`

There was no redirect or any other kind of 3D secure form displayed.

Many thanks for any help you can offer.

Phill

**Comment by phillmorgan28** [comment]
Further to this, I updated the gateway on my tests to Stripe Payment Intents, however I now receive the attached screenshot.

![image](https://user-images.githubusercontent.com/13579386/62531075-9bea9700-b839-11e9-84f1-563ec1b02499.png)

The URL to receive that was:

https://stripe.com/sources/test_source_3ds2?amount=54900&currency=gbp&livemode=false&return_url=https%3A%2F%2Fhooks.stripe.com%2F3d_secure%2Fcomplete%2Ftdsrc_1F4PT9G6t8CScTBlWDZw32Dn&source=src_1F4PT4G6t8CScTBlQRVB7ijF&statement_descriptor=REMOVED&type=three_d_secure_2_eap&usage=single_use

I looks like some kind of redirect is happening for 3Ds2 but Stripe is unable to handle it.

**Comment by andris-sevcenko** [comment]
If I click that link, the 3DS page displays just fine. Are you still experiencing difficulties?

**Comment by phillmorgan28** [comment]
Ah! Same for me now as well. Must really have been issues at Stripe. Sorry for the re-open, looks like I'm all set!

**Comment by andris-sevcenko** [comment]
Glad that's all it was!
