### ISSUE TITLE
EVENT_BUILD_GATEWAY_REQUEST not merging data correctly

### ISSUE THREAD

**Issue by chadcrowell** [craftcms/commerce-stripe#58]
I'm writing a plugin to take the order.reference field from the order, and put it into the Stripe payload using the EVENT_BUILD_GATEWAY_REQUEST event. 

in the comments above Gateway.php: 102, it is noted that changes can be made. Looking at line 979 where the event runs, we can see the $event contains $transaction, $metadata, and $request. The comments say we can't change $transaction, so we can change these fields:

```
$metadata = [
            'order_id' => $transaction->getOrder()->id,
            'order_number' => $transaction->getOrder()->number,
            'transaction_id' => $transaction->id,
            'transaction_reference' => $transaction->hash,
        ];
```
and
```
$request = [
            'amount' => $transaction->paymentAmount * (10 ** $currency->minorUnit),
            'currency' => $transaction->paymentCurrency,
            'description' => Craft::t('commerce-stripe', 'Order') . ' #' . $transaction->orderId,
            'metadata' => $metadata
        ];
```

My plugin changes the value of $metadata['order_id'] and $request['description'] to include the order.reference. When I var_dump $event just after the event runs (line 980), I can see my data in the arrays. However, if I dump $request on line 984, after the $event data is merged into $request, I see the original data in $request.

Looking at the php docs for array_merge, the first param supplied should be the original array, and second param should be the array with potentially changed data, any of which are changed will overwrite those same keyed values in the original array. You array_merge code on 982 is:

```
$request = array_merge($event->request, $request);
$request['metadata'] = array_merge($event->metadata, $metadata);
```

which suggests that values in $request will overwrite those in $event->request (and the same with $metadata in the second line). Instead, it should be this:

```
$request = array_merge($request, $event->request);
$request['metadata'] = array_merge($metadata, $event->metadata);
```

so that any changed data in $event->request will overwrite those in $request, which is the original array (same in the second line). 

This change did get my modified data over to Stripe. Hopefully it didn't wreck anything else :)

**Comment by andris-sevcenko** [comment]
Did your changes to `$request['description']` make it to Stripe before you made changes to the code? If so, then everything is working as expected. 

The [doc block for the event](https://github.com/craftcms/commerce-stripe/blob/af7fe165737cce8a1b4523dc46aec353a9c9995d/src/gateways/Gateway.php#L86) states 
> Note, that any changes to the `Transaction` model will be ignored and it is not possible to set `order_number`, `order_id`, `transaction_id`, `transaction_reference`, and `client_ip` metadata keys.

**Comment by chadcrowell** [comment]
No changes made it to Stripe before I made the described change. The changes my plugin makes are:

```
$e->metadata['order_id']
$e->request['description']
$e->request['metadata']['order_id']
```

The Stripe plugin appears to be sending these arrays to Stripe:

```
$event = new BuildGatewayRequestEvent([
                'transaction' => $transaction,
                'metadata' => $metadata,
                'request' => $request
            ]);
```

I haven't touched the transaction model, only metadata and request. None of those changes made it to Stripe before this change.

**Comment by andris-sevcenko** [comment]
Oh, I'm sorry. I misread the original issue. Those are protected for a reason to maintain an immutable reference to Commerce. Not sure I'd want to allow overriding those properties.

What about if I add an `order_reference` metadata key/value pair as well as add the reference in parenthesis to the `description` key? This way I get to keep the immutable reference to Commerce, and you get your reference number into Stripe.

**Comment by chadcrowell** [comment]
That seems like a reasonable way to handle it. It just seems weird that Commerce would allow custom consecutive order numbering via order.reference, but without doing something like this, it never gets sent to Stripe so that there is a visual connection between the orders in the Control Panel and the payments in Stripe. Thanks!

**Comment by andris-sevcenko** [comment]
Well. The order reference was added on November last year and updating Stripe to send that over sort of slipped through the cracks :(

**Comment by andris-sevcenko** [comment]
Eh, so here's the tricky part. The reference only gets generated once the order is completed. When attempting payment, the order is not completed yet.

Talked with @lukeholder about this and the best course of action seems like it would be a custom plugin/module that listens to the `Order::EVENT_AFTER_COMPLETE_ORDER` event, figures all it needs to figure out by looking at the transaction (if it's a Stripe gateway, what API was used (Charge or Payment Intents)) and then updates the existing charge/payment intent with the reference information.

The reason we don't feel like this should be a part of this plugin is because there already is a solid link between the payments and orders as the order id is exposed. Furthermore, you can display the order id in the order listing page. And going even further, if you go to an order's page, you can see detailed information for every transaction.

**Comment by andris-sevcenko** [comment]
> then clobbers the data that is modified because the array_merge functions has the arrays listed backward in the code.

They are listed that way intentionally so that plugins can't override the data defined there.

If anything, the event documentation should be updated by listing all the other things that can not be overwritten, something I neglected to do in https://github.com/craftcms/commerce-stripe/commit/04a1cdf334e98f86f17fd7c7934d9dac25614cc4

**Comment by lukeholder** [comment]
We can't allow editing of the `order_id` or `order_number` (or the other things we send to Stripe) in the request's meta data. We should make the clear in the Phpdocs and docs.

You can add any extra data to the request that you wish. Sorry for the confusion.

**Comment by cliveportman** [comment]
Hi. The description provided to Stripe is not informative and we need the ability to provide our own. Most of our clients export the data provided by Stripe to reconcile their accounts and not having a decent description is a major inconvenience for them.

Can't you just add the following line, keeping everything else intact?
```$request['description'] = $event->request['description'];```

**Comment by chadcrowell** [comment]
@cliveportman I have a plugin that overrides certain vars in the $request array if you want it I can send it to you. It requires an easy hack in the Stripe Commerce plugin but it works for my 2 clients. You just have to reimplement the hack whenever the Commerce Stripe plugin is updated or if you delete and rebuild the vendor folder.

**Comment by GaryReckard** [comment]
I'm encountering this same issue. I'm using the `EVENT_BUILD_GATEWAY_REQUEST` event, and modifying the `$e->request['description']`, and adding an additional metadata  `$e->request['metadata']['order_reference']` (also tried `$e->metadata['order_reference']`). But my changes never make it past these lines: https://github.com/craftcms/commerce-stripe/blob/55233f76b747fbb09fd79d0dce3db2d0a935d427/src/base/Gateway.php#L368-L369

I suggest changing that line to:
`$request = array_merge($request, $event->request);` 
and leaving the metadata on as it. That should preserve the unchangeable metadata, as well as any additions made through the event.

But as it stands, that event is pointless, as nothing can get changed.

**Comment by chadcrowell** [comment]
@GaryReckard yep I'm still hacking Stripe Commerce with every update to it in order to get more readable order details over to Stripe for 2 clients... P&T won't change the way the data is sent.

**Comment by GaryReckard** [comment]
I did find that, since I had been updating `$e->request['metadata']['order_reference'] = $reference;` in my event handler, my changes were getting wiped out. I didn't use `$e->metadata` because `BuildGatewayRequestEvent` said that was deprecated. If I use that, my new metadata does make it over to stripe.

So for now, I'm just specifying both:
```
        Event::on(StripeGateway::class, StripeGateway::EVENT_BUILD_GATEWAY_REQUEST, function(BuildGatewayRequestEvent $e) {
            $reference = substr($e->request['metadata']['order_number'],0,7);

            $e->request['metadata']['order_reference'] = $reference;
            $e->metadata['order_reference'] = $reference;

            $e->request['metadata']['order_email'] = $e->transaction->order->email;
            $e->metadata['order_email'] = $e->transaction->order->email;

            $e->request['metadata']['order_billing_email'] = $e->transaction->order->billingEmail;
            $e->metadata['order_billing_email'] = $e->transaction->order->billingEmail;

            $e->request['metadata']['purchase_order_number'] = $e->transaction->order->referenceNumber;
            $e->metadata['purchase_order_number'] = $e->transaction->order->referenceNumber;

            $e->request['description'] = "Order #".$reference;
        });
```

Sadly, my update to 'description' gets wiped out 👎

**Comment by chadcrowell** [comment]
I update just these 3 fields but they do correctly update in Stripe:

$e->metadata['order_id']
$e->request['description']
$e->request['metadata']['order_id']
