### ISSUE TITLE
Country ISO in payment intents

### ISSUE THREAD

**Issue by tom-c** [craftcms/commerce-stripe#59]
Just trying the Stripe gateway for the first time and have received an error back from Stripe when checking out. They need the country ISO rather than country name in the address details submission. 

I've temporarily edited paymentForms/intentsForm.html and changed {{ billingAddress.country }} to {{ billingAddress.country.iso }}.

Testing with UK addresses and it was failing when using 'United Kingdom' in the address, now works when it's 'GB'.

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this.
When are you seeing this error and what is the error exactly?

Also, which gateway is this?

For reference - here are screenshots from Stripe Dashboard for Payment Intents API when creating a payment method (entering credit card details and clicking "pay") - https://imgur.com/a/Ur43mge

**Comment by tom-c** [comment]
Hmm, curious. 

Using the Stripe Payment Intents gateway.

Looks like the error message is Ajax loading into the payment intents element within the public site. Just using the standard example templates that come with commerce currently.

Testing payments with Stripe test mode and their test card numbers - perhaps that's what's throwing it? But adding the country.iso into the template as mentioned above makes it work.

Here's a screenshot of the element within the checkout http://trans.adart.cc/30a5441d1f4f

**Comment by tom-c** [comment]
I've tracked down the event in the Stripe dashboard and it's almost identical to what you've tested with, but shows a 400 error. https://imgur.com/a/F6ybpfO

The only difference I can see is I used a full UK postcode, so perhaps that triggers Stripe to validate the country code?

**Comment by andris-sevcenko** [comment]
Hmm, can't reproduce with a full postcode. I'm also using test mode with the test card numbers.

What Stripe API version have you set as the default in Stripe Dashboard?

**Comment by tom-c** [comment]
It's defaulting to an old one 2013-10-29 but also says 'You may be using multiple API versions due to your client libraries or plugins'.

Will switch to a new one - wasn't even aware of that ability so will investigate and retest.

**Comment by andris-sevcenko** [comment]
Let me know, yeah. The "Multiple API version" thing is there because this plugin currently uses the "2019-03-14" version, but that's only for backend requests. Pretty sure that the public requests use the default API version set for the account - that might be the reason for this behavior you're seeing.

**Comment by tom-c** [comment]
Updated the default API in Stripe dash to '2019-05-16 (latest)' but it's still giving the same error and details shown the screenshot above..

**Comment by tom-c** [comment]
Just ran again with all the details you've used in your test and it's still failing. Could it be because I'm in the UK.

Here's a redirect to the dev site if you want to try yourself: http://trans.adart.cc/0db91f2234dd

**Comment by tom-c** [comment]
Also just tried a much cheaper product test to be sure that it's not a Stripe enforcement on high price items. Still no luck :(

**Comment by philipboomy** [comment]
I am getting this too.

> Country 'United Kingdom' is unknown. Try using a 2-character alphanumeric country code instead, such as 'US', 'EG', or 'GB'. A full list of country codes is available at https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
> 

If I change the the country "United Kingdom" to "GB" then it works. https://cl.ly/28b34ea598f5

Stripe API version is latest https://cl.ly/e7b7745f41fa

**Comment by andris-sevcenko** [comment]
Huh. Definitely can't make the payment on your site. If I take the cURL request and replay it with my public key, it goes through, so I can only conclude that it's something happening on Stripe's end that depends on something in settings or some metadata for the Stripe account.

Either way, if I switch to the ISO code and switch back to using the "I produce errors" publishable key, the errors go away. So, even though I wasn't able to conclude exactly what triggers this, using ISO code produces no errors for all parties involved, so that's what we'll do.

**Comment by andris-sevcenko** [comment]
Just released 2.0.1 which addresses this.

**Comment by andris-sevcenko** [comment]
Pun not intended. :)

**Comment by tom-c** [comment]
Ace. thank you for investigating and applying the fix.

**Comment by bymayo** [comment]
I'm having the opposite issue now when using this for Subscriptions.

The Billing Address isn't defined, so unsure why the below code is even rendering:

```
    {% if billingAddress is defined %}
        <div class="stripe-address hidden">
            <input type="hidden" name="stripe-line1" value="{{ billingAddress.address1 }}" />
            <input type="hidden" name="stripe-postal-code" value="{{ billingAddress.zipCode }}" />
            <input type="hidden" name="stripe-city" value="{{ billingAddress.city }}" />
            <input type="hidden" name="stripe-country" value="{{ billingAddress.country.iso }}" />
            <input type="hidden" name="stripe-state" value="{{ billingAddress.state }}" />
        </div>
    {% endif %}
```
But if I remove the `iso` off `{{ billingAddress.country.iso }}` it works fine and subscription payment goes through perfectly.

**Comment by andris-sevcenko** [comment]
Billing address is populated from the customer's primary billing address and it's there to reduce the chance of transactions being flagged as fraudulent.

> I'm having the opposite issue now when using this for Subscriptions.

You'll have to elaborate a little on this, though.

**Comment by bymayo** [comment]
> > I'm having the opposite issue now when using this for Subscriptions.
> 
> You'll have to elaborate a little on this, though.

If the billing address is not defined, or is null these hidden fields shouldn't render surely? At the moment I'm getting a `iso` doesn't exist on a null variable, which i'm guessing is because `billingAddress.country` is null. 

We've got subscriptions setup and previously we never needed to ask for a billing address (You generally don't with Stripe) so is this now required with Payment Intents?

**Comment by andris-sevcenko** [comment]
> At the moment I'm getting a iso doesn't exist on a null variable, which i'm guessing is because billingAddress.country is null.

Ah, okay, have to be more defensive there, then. I'll see if I can get a patch out today.

> We've got subscriptions setup and previously we never needed to ask for a billing address (You generally don't with Stripe) so is this now required with Payment Intents?

It's not required, just good practice. The `billingAddress` is defined if the current customer has a primary billing address set. It's just an oversight that the `country` might not be defined on it.

**Comment by agoyal0422** [comment]
I was having the same issue and the way I fixed it was by going where I was defining payload 

const payload = await stripe.confirmCardPayment(clientSecret.... and changing it from just country: country; to country: country.iso;


<img width="595" alt="Screen Shot 2021-05-22 at 5 40 45 PM" src="https://user-images.githubusercontent.com/64865827/119242602-d7e11000-bb24-11eb-81cc-7679cc8c516e.png">
