### ISSUE TITLE
Guest checkout with Payment Intents

### ISSUE THREAD

**Issue by tom-c** [craftcms/commerce-stripe#60]
It seems I've found a bug in the new payment intents system. Guest checkouts are failing with a 'Undefined variable: customer' banner.

I can see that logged in checkouts are sending the right web hooks (log on the Stripe dashboard is showing the customer creation etc) however when a user is a guest the web hooks are not called, thus not setting up the customer before making payment (or so it seems).

This is only with the new Payment Intents, regular Checkout is working fine (but not with the test cards for 3DS 2).

Hopefully I've missed something obvious but pulling blanks with this.

**Comment by andris-sevcenko** [comment]
Thank you!

**Comment by andris-sevcenko** [comment]
Just released 2.0.1 which addresses this.
