### ISSUE TITLE
Webhook Signing Secret and ENV not playing nicely

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce-stripe#61]
The env key for the signing secret is not saving in the CP Stripe Gateway Settings, we were moving all settings into the .env file and it just reverts to the original value, not the env key, when saved. Imagine it's just displaying incorrectly.

Stripe for Craft Commerce - 2.0.1.1
Craft Commerce - 2.1.6.1
Craft CMS - 3.1.29

**Comment by jacobgraf** [comment]
Same thing here.

**Comment by matthewbeta** [comment]
Same here. We are also seeing the key set in the `project.yaml` file as plain text, as opposed to the environment variable. This is a bit scary. It's an issue having the key in version control at all, but also every deploy of the `project.yaml` is going to override the live key with the test key.
