### ISSUE TITLE
Customize Payment Intent Form

### ISSUE THREAD

**Issue by DidoMarchet** [craftcms/commerce-stripe#65]
Hi,
maybe this is not the right place to ask this question but
I'm trying to create my custom styled form for Stripe Intens payment.

I've seen it uses the CreditCardFiels of craft commerce.
Below the fields I've used for form. 

```
<input type="hidden" name="gatewayId" value="3"/> // My gateway ID for Stripe
<input type="hidden" name="action" value="commerce/payments/pay"/>
{{ redirectInput(url('shop/customer/order?register='~cart.registerUserOnOrderComplete~'&number='~cart.number)) }} // My redirect url
<input type="hidden" name="cancelUrl" value="{{ url('shop/checkout/payment')|hash }}"/> // My Cancel Url 
{{ csrfInput() }}

<input type="text" name="firstName">
<input type="text" name="lastName">
<input type="text"  name="number">
<select name="month">.... </select>
<select  name="year">.... </select>
<input type="text" name="cvv">
```
Whit Stripe Charge it works
but not with Payments Intents. There's something I've forget?

Do you have any doc how to customize the form?

Thanks in advance and regards,

Davide

**Comment by lukeholder** [comment]
Hi Davide,

For stripe's payment intents, commerce's pay controller action (commerce/payments/pay) only cares about receiving a paymentMethodId which is a token generated by stripe javascript which you can read about here: https://stripe.com/docs/payments/payment-intents/quickstart#collect-payment-method

The other credit card inputs are there to generate that paymentMethodId token.

In the default gateway.paymentFormHtml({}) we have written javascript as per the stripe docs to do this.

You can find that in vendor/craftcms/commerce-stripe/src/web/assets/intentsform/js/paymentForm.js and vendor/craftcms/commerce-stripe/src/templates/paymentForms/intentsForm.html

Hope that helps.


-Luke

**Comment by kamicrafted** [comment]
@lukeholder is it possible to customize the input styling (cc, expiration and cvc) at all using the plugin? paymentForm.js doesn't seem to have a way to add input field styling and the Stripe documentation seems to use a separate CSS file in addition to the base styles that are defined in the js file.

Any advice would be much appreciated, thank you 🙏

**Comment by nfourtythree** [comment]
@kamicrafted this question has been asked on Stack Exchange. I have provided and answer there: https://craftcms.stackexchange.com/questions/30679/customizing-stripe-payment-form-for-craft-commerce-2-subscription/33168#33168

**Comment by RoussKS** [comment]
@nfourtythree it would actually be great if a configuration object was accepted as params in the default ` gateway.paymentFormHtml({}) ` that would then be loaded on instantiating the elements and replace the style object etc.

This way, if there's a stripe library update, you can change your asset bundle, noone misses functionality and doesn't need to write custom code to achieve this.

The other way around this from what I can see is to replace the asset bundle component js file with a custom one, through the app configuration.
The native card holder input fields can just be styled through a css file targeting the first/last name input elements.
