### ISSUE TITLE
Upgraded to 3.2 and getting an error "At least one block type is required."

### ISSUE THREAD

**Issue by sunscreem** [craftcms/commerce-stripe#68]
Just upgrade a site to 3.2.6 & the latest version of this plug in (1.9.8). All seemed fine (testing on the front end and test payments going through no problem).

Only issue is when I access any payment form either and existing one or a new one I get:

![image](https://user-images.githubusercontent.com/7523595/62057385-7943f700-b217-11e9-9f38-886dba0b4823.png)

(My local url when this error comes up is http://clientdomain.test/admin/enupal-stripe/forms/edit/3607)

**Comment by andris-sevcenko** [comment]
You're looking for https://github.com/enupal/stripe

**Comment by sunscreem** [comment]
![giphy](https://user-images.githubusercontent.com/7523595/62070161-dba9f100-b231-11e9-8172-cff0d6d1703e.gif)
