### ISSUE TITLE
Cannot update request description using EVENT_BUILD_GATEWAY_REQUEST

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce-stripe#69]
The $event->request is overwritten by the original $request intentionally but I think it's important we can update descriptions. Clients frequently export from the Stripe dashboard to reconcile their accounts and the description field is next-to-useless at the moment.

Please see my comment in response to:
https://github.com/craftcms/commerce-stripe/issues/58

**Comment by lukeholder** [comment]
Fixed in #85
