### ISSUE TITLE
Stripe Gateway Property Exception : includeReceiptEmailInRequests

### ISSUE THREAD

**Issue by magnessjo** [craftcms/commerce-stripe#7]
@andris-sevcenko,

  In reference to [284](https://github.com/craftcms/commerce/issues/284)

  I updated my commerce config for the new attribute name.  The error is still shown.  I was able to get the error to go away with a mysql update (see below).  My issue is resolved so this can be closed, but should it be part the migration for Commerce?  

Update craft_commerce_gateways set settings = '{"apiKey":"<YourKey>","publishableKey":"<YourKey>","sendReceiptEmail":""}' where id = <YourId>;

**Comment by andris-sevcenko** [comment]
Good call. Install migration for Stripe should have erased that from settings. I'll make sure that this happens.

**Comment by andris-sevcenko** [comment]
Thanks again!

**Comment by magnessjo** [comment]
@andris-sevcenko,

  Your welcome. Thanks for the fix.
