### ISSUE TITLE
subscription.getNextPaymentAmount no longer JSON

### ISSUE THREAD

**Issue by cliveportman** [craftcms/commerce-stripe#71]
### Description
SubscriptionData is no longer JSON, so:

```{{ subscription.getNextPaymentAmount() }}```

gives the error "Invalid JSON data." because of line 147 in Commerce Stripe's base\SubscriptionGateway.php:

```$data = Json::decode($subscription->subscriptionData);```

### Steps to reproduce
1. Grab a subscription and call {{ subscription.getNextPaymentAmount() }}

### Additional info
Fix by removing JSON decode from line 147 of commerce-stripe\src\base\SubscriptionGateway.php

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions: Craft Commerce 2.1.10, Stripe for Craft Commerce 2.0.1.2

**Comment by lukeholder** [comment]
The `getNextPaymentAmount` error has been fixed for the next stripe release.

@medoingthings you shouldn't need to `json_decode` that in your templates anymore, it is now just considered an array.

@andris-sevcenko
