### ISSUE TITLE
Use Order Reference Number For Stripe Description 

### ISSUE THREAD

**Issue by siebird** [craftcms/commerce-stripe#72]
Currently, the plugin is using the transactions `order.id` for descriptions at Stripe. For reconciling purposes, my client is having a hard time referencing since we are using sequential order numbers. It would be great if the description at Stripe used the `order.reference` to keep things consistent.

**Comment by mufi-siebird** [comment]
Happen with me too. I change reference number and Stripe shows Order #{orderid}. Would be great if Stripe description matches with Order Reference instead of order ID.

**Comment by mufaddalsmart1** [comment]
Happen with me too. I change reference number and Stripe shows Order #{orderid}. Would be great if Stripe description matches with Order Reference instead of order ID.

**Comment by andris-sevcenko** [comment]
The order reference is generated after the order is completed. The order is completed after the transaction has been made, so it's a catch-22 here. At the time of transaction, the order id is the only feasible way of tying those two together. 

The best course of action would be to have a custom plugin listen to the [right event](https://docs.craftcms.com/commerce/v2/events.html#the-aftercompleteorder-event) and then update the appropriate transaction on Stripe.

**Comment by amos-whitewolf** [comment]
Also finding this frustrating, Is it possible to use the order number generated when the cart is created in the stripe description rather than the order ID?
