### ISSUE TITLE
Payment gateways are not synced.

### ISSUE THREAD

**Issue by saxenapritesh** [craftcms/commerce-stripe#76]
```
Craft solo : 3.1.25
Craft Commerce : Lite ( 2.1.12.1)
```

I am trying to integrate it with `craft Lite` for subscription plan.

- I Created 1 product at stripe account.

- Added stripe keys to my local store.

- Payment is working in test mode. ( so keys are correct)

![no-gateway](https://user-images.githubusercontent.com/26432256/63781717-ce9f2100-c907-11e9-8cf9-5648a2028bed.png)

In settings/subscriptions/plans i created 1 plan and after clicking the refresh button all the products on stripe are shown.I selected the product and save the subscription, but after reloading the page gateway name is changed to subscription plan name.

All the stripe products are fetched.

![Screenshot from 2019-08-28 17-29-10](https://user-images.githubusercontent.com/26432256/63853880-71fc3e80-c9b9-11e9-8421-8f6f47cdb9ce.png)

After reloading the page gateway changed to Plan name ( website subscription plan)
![Screenshot from 2019-08-28 17-29-30](https://user-images.githubusercontent.com/26432256/63853881-71fc3e80-c9b9-11e9-8c9c-6e96b4dc4535.png)

What i am missing ?

**Comment by maddyBoy** [comment]
I am facing the same issues even on fresh setup with updated plugins.

There is no error log in the console.

**Comment by andris-sevcenko** [comment]
> I selected the product and save the subscription, but after reloading the page gateway name is changed to subscription plan name.

Where? The only place where you can see the gateway name on the `Edit Plan` page is in the gateway dropdown and it doesn't change there.

**Comment by andris-sevcenko** [comment]
Ah, ok, I see what you mean.

**Comment by andris-sevcenko** [comment]
The actual plan name is not changed, it's just a cosmetic error.

@nfourtythree Probably worth normalizing the experience between https://github.com/craftcms/commerce-stripe/blob/develop/src/base/SubscriptionGateway.php#L317-L319 and https://github.com/craftcms/commerce-stripe/blob/develop/src/templates/planSettings.html#L6

**Comment by maddyBoy** [comment]
@nfourtythree is there any path for this issue or it's going to solve in near future release?

**Comment by andris-sevcenko** [comment]
@maddyBoy to clarify - the only issue here is that the wrong plan name is displayed when editing the subscription plan. It is not saved incorrectly in the database - just the incorrect name is displayed. It will be solved eventually, but it's hardly a priority.

**Comment by lukeholder** [comment]
This was fixed in https://github.com/craftcms/commerce-stripe/blob/develop/CHANGELOG.md#221---2019-10-29
