### ISSUE TITLE
SCA ready?

### ISSUE THREAD

**Issue by satcreative** [craftcms/commerce-stripe#77]
As [Strong Customer Authentication](https://stripe.com/gb/guides/strong-customer-authentication) (SCA) regulation come into affect for Europe, on 14th September, is this plugin compliant or will it result in failed transactions from the 14th September?

**Comment by andris-sevcenko** [comment]
The Payment Intents is SCA ready and was added back in May (https://github.com/craftcms/commerce-stripe/blob/develop/CHANGELOG.md#200---2019-05-14)
