### ISSUE TITLE
Payment Intents error

### ISSUE THREAD

**Issue by cole007** [craftcms/commerce-stripe#79]
Not sure if issue with set-up or because I'm working with the test API.

Experiencing an issue using Payment Intents where if an attempt to redirect to 3D secure page is not completed then subsequent attempts to submit card details on a payment page are hit with the following error response from Stripe:

    This PaymentIntent's amount could not be updated because it has a status of requires_action. You may only update the amount of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation.

Not sure if this is expected behaviour but a confusing message to get back (and not something can easily convey back to users).

Context:

Craft CMS 3.3.3
Craft Commerce 2.1.13
Stripe for Craft Commerce 2.1.2

Stripe API 2019-03-14

This is using the out-of-the-box Craft Commerce templates.

**Comment by andris-sevcenko** [comment]
I cannot reproduce this locally. Are you using the example Commerce templates or something custom?

**Comment by cole007** [comment]
This is with the out-of-the-box templates as well as custom

**Comment by nfourtythree** [comment]
Hi @cole007 

I have just tried to replicate this with a fresh install and the example templates. I have put together a [quick video](http://x.n43.me/2faf4b1c9de0) of failing a payment then making a successful payment just to make sure we are talking about the same thing.

Let me know if this is the same process you are going through.

Thanks.

**Comment by lukeholder** [comment]
@cole007 let us know if this is still an issue and we will re-open

**Comment by paulmendrik** [comment]
I do have another issue which happened after the latest major Craft and Commerce updates. The Craft Commerce Stripe plugin for the stripe gateway I use was working fine before the update but now I'm getting a HTTP 400 Bad Request , Request contains invalid body param (see attached image)
![error](https://user-images.githubusercontent.com/29773409/91833314-d5612200-ec46-11ea-87f4-0ddbae01dc22.png)
. I'm using the following to create the payment form:

<form method="POST">
<input type="hidden" name="action" value="commerce/payments/pay"/>
<input type="hidden" name="redirect" value="/commerce/customer/order?number={number}"/>
<input type="hidden" name="cancelUrl" value="{{ '/shop/checkout/payment'|hash }}"/>
{{ csrfInput() }}

{{ cart.gateway.getPaymentFormHtml({})|raw }}

<div class="uk-form-controls uk-margin-large-top">
<button type="submit" class="uk-button uk-button-secondary">Pay {{ cart.totalPrice|commerceCurrency(cart.paymentCurrency,convert=true) }}</button>
</div>

</form>

Finally, I also checked the logs in stripe it gives a 200 O.K. without finalising the payment.

Any ideas ?

**Comment by joneslafuente** [comment]
I am trying to update a site for somebody to integrate SCA. Have updated the CMS to version 3, also Commerce 3 all setup but getting failed payments and the same 200 OK in the Stripe dashboard logs. Fails when trying a payment from the control panel. All API keys and web hook are setup correctly.

Thanks, any help appreciated.
