### ISSUE TITLE
Cancelling subscription in Stripe dashboard does not cancel it in Craft

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/commerce-stripe#83]
Title pretty much says it all. I'd expect this plugin to handle such an integration.

**Comment by andris-sevcenko** [comment]
Did you cancel the subscription immediately or is it still active and will be terminated once the current billing cycle ends?

**Comment by thisisjamessmith** [comment]
Immediately

**Comment by andris-sevcenko** [comment]
Have you set up the webhooks correctly? Can you check by going in the appropriate subscription on Stripe Dashboard, selecting the appropriate event for the subscription on the subscription page, and then checking the webhook status at the end of the event page?

**Comment by thisisjamessmith** [comment]
Thanks Andris, checked and all that appears ok, the webhook returns a 200 success. Are you suggesting this is supposed to work out of the box? I assumed it just wasn't part of the built-in functionality.

**Comment by thisisjamessmith** [comment]
In the interim, what's the best way for me to delete all subscriptions from Craft? I've been doing loads of tests and 3rd party integrations, resulting in 100+ subscriptions being created, now need to clean them all up and delete associated test users.

**Comment by andris-sevcenko** [comment]
> Thanks Andris, checked and all that appears ok, the webhook returns a 200 success. 

Huh, anything in the logs? It should be working out of the box, yeah.

> In the interim, what's the best way for me to delete all subscriptions from Craft? I've been doing loads of tests and 3rd party integrations, resulting in 100+ subscriptions being created, now need to clean them all up and delete associated test users.

You can just nuke them from the database, I would assume. Or, better, once we figure out why the webhook didn't trigger properly, terminate them from Stripe dashboard.

**Comment by thisisjamessmith** [comment]
If I wanted to delete direct from the database, which tables do I need to worry about... If I just `DELETE * FROM craft_commerce_subscriptions` it'll orphan some rows in `craft_elements` and maybe others...?

**Comment by thisisjamessmith** [comment]
Stripe logs show the same 200 success messages on subscription deletions

**Comment by andris-sevcenko** [comment]
> Stripe logs show the same 200 success messages on subscription deletions

I meant Craft logs, sorry!

> If I wanted to delete directly from the database, which tables do I need to worry about

Ideally, you'd delete the `craft_elements` records and everything should cascade nicely!

**Comment by thisisjamessmith** [comment]
Ah, so the Craft log shows an error:

```
2019-10-07 12:05:29 [-][-][-][warning][stripe] Webhook signature check failed: No signatures found matching the expected signature for payload
2019-10-07 12:05:29 [-][-][-][info][application] $_GET = [
    'p' => 'actions/commerce/webhooks/process-webhook'
    'gateway' => '2'
]
```

I've double-checked the settings for the webhook signing secret and API keys and all 3 are correct.

Great to know I can delete from `craft_elements` and let MySQL cascade from there, I was never 100% comfortable doing that!

**Comment by andris-sevcenko** [comment]
> No signatures found matching the expected signature for payload

That's odd. That code is thrown by the Stripe library if the signatures don't match. I know this sounds stupid, but can you triple-check? Maybe some encoding, escaping or leading/trailing whitespace issue? Maybe try modifying the [code here ](https://github.com/craftcms/commerce-stripe/blob/develop/src/base/Gateway.php#L168-L176)to give you more information when throwing the exception?

**Comment by thisisjamessmith** [comment]
oohh, hold on a minute, the signing secret was not quite identical, I have no idea how that happened! Ok, we're fixed up now. Sorry for the bother.

**Comment by andris-sevcenko** [comment]
No problem - glad that's all it was!

**Comment by andris-sevcenko** [comment]
As far as the subscription wipe goes 

>  Or, better, once we figure out why the webhook didn't trigger properly, terminate them from Stripe dashboard.

This is a better approach, as just deleting the DB rows won't cancel the subscriptions on Stripe end. Deleting them from Stripe dashboard would ensure all of them are terminated cleanly and then you can just nuke them to oblivion.
