### ISSUE TITLE
Queue run initialisation JavaScript in webhook responses

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/commerce-stripe#86]
_Craft: 3.3.6
Commerce (Pro): 2.1.13
Stripe for Commerce: 2.1.2_

In WebHook responses, the Stripe control panel occasionally indicates a response like the following:

```html
ok<script type="text/javascript">
/*<![CDATA[*/
(function(){
    var XMLHttpFactories = [
        function () {return new XMLHttpRequest()},
        function () {return new ActiveXObject("Msxml2.XMLHTTP")},
        function () {return new ActiveXObject("Msxml3.XMLHTTP")},
        function () {return new ActiveXObject("Microsoft.XMLHTTP")}
    ];
    var req = false;
    for (var i = 0; i < XMLHttpFactories.length; i++) {
        try {
            req = XMLHttpFactories[i]();
        }
        catch (e) {
            continue;
        }
        break;
    }
    if (!req) return;
    req.open('GET', "https://[***hostname***]/index.php?p=actions/queue/run", true);
    if (req.readyState == 4) return;
    req.send();
})();
/*]]>*/
</script>
```

While (at the moment) Stripe seems OK with this I'm not sure it's intended behavior. Looking at the code in `vendor/craftcms/cms/src/queue/Queue.php`, if the Stripe WebHook changed it's response content-type to `text/plain`, that might sort things out?

I would guess that setting the config variable `runQueueAutomatically` to false might help this? (but that is not something I can do at this point - working towards it though)

**Comment by lukeholder** [comment]
Fixed in 48e7627a254b29fcd45180cd00dfa5321ba3f168 will be in next release.
