### ISSUE TITLE
Using SEPA/IBAN as a payment source for subscriptions

### ISSUE THREAD

**Issue by medoingthings** [craftcms/commerce-stripe#90]
Payments for my subscriptions using credit cards are working fine. Now I’m trying to get SEPA payments to work. I’ve already set it up in the Stripe dashboard.

I followed the [Stripe documentation](https://stripe.com/docs/sources/sepa-debit#create-source) and the only difference seems to be that the generated token comes from the `stripe.createSource` method as opposed to the `stripe.createToken` method (when submitting a credit card source).

So my expectation was that this should just work. But it doesn’t. 

**Question:** Am I doing something wrong or are SEPA payment sources not supported by commerce-stripe, yet?

Any hint is much appreciated.

Cheers,
Mark

**Comment by lennartlott** [comment]
Any updates on this issue?

**Comment by pimago** [comment]
Please give some love to European users and add this feature. Not everyone uses credit card over here. Stripe supports a lot of payment methods with recurring payments.

**Comment by medoingthings** [comment]
@pimago have you checked out the latest version of commerce-stripe? It now uses Stripes Payment Intents: https://github.com/craftcms/commerce-stripe#payment-forms

Not sure if that enables IBAN, but it might be worth giving it a try.

**Comment by pimago** [comment]
Hey Mark. Yes I just tried that. But it looks like it doesn't support recurring payments. Only when I add a credit card as payment source I can start a subscription.

**Comment by medoingthings** [comment]
Good to know. That might be an implication that has nothing to do with Craft, but with the finance system. 

In order to "pull money from somebody elses bank account" you need (in Germany/EU) a „Lastschriftmandat” that has to be signed by the customer. So it’s a more complicated than using a credit card. Stripe has information regarding this on their website: https://stripe.com/de-us/resources/more/sepa-authorization-and-cancellation (german).

**Comment by medoingthings** [comment]
Hmm… here is more information on the Stripe website on how to do it with Stripe:
https://stripe.com/docs/billing/subscriptions/sepa-debit

**Comment by pimago** [comment]
On stripe I can create a Payment Link and it was possible to create subscription with Sepa debit. At least in test mode it worked.

**Comment by lukeholder** [comment]
We released an update in 4.1.1 that fixed a bug where not all enabled payment methods types were being shown when creating a payment source. All supported recurring methods are now available.
