### ISSUE TITLE
Syntax error in paymentForm.js in older browsers

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/commerce-stripe#92]
The `/web/assets/intentsform/js/paymentForm.js` file for payment Intents throws a syntax error in row 24 in older browsers (like iE11) as those don't have support for ES6 classes. 

You don't mention any browser limitations in your documentation so either it would be appreciated if you did or if you added support for the same browsers as Stripe officially support (Stripe supports IE10+). I vote for the latter one :)

Thanks!

**Comment by nfourtythree** [comment]
Have fixed this and will be in the next release of the plugin.
