### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/commerce-stripe#93]
It would be really nice if you could either drop the jQuery dependency in the javascript files or make it possible to choose if the plugin should load the jQuery library or not.

Now the jQuery library loads twice on the checkout page if the site uses jQuery (once from the site and once from Commerce Stripe) which mess up some other javascript code on the page. So after every Commerce Stripe update we need to remove the jQuery library from loading in the plugin...

Thanks!

**Comment by lukeholder** [comment]
The payment form methods like `getPaymentFormHtml()` were designed for the backend payment forms only. We include them in the example templates for convenience. 

You would need to implement the front end JS yourself if you want to have complete control over the JS.

The control panel JS also only targets Microsoft Edge+ and other [recent browsers](https://docs.craftcms.com/v3/requirements.html#control-panel-browser-requirements), so using our control panel form methods might not match your front end browser support requirements.

**Comment by lukeholder** [comment]
Welcome PRs that remove jQuery dependance though - it's just that we know we have jQuery in the CP with our Yii AssetBundle system.

**Comment by mufi-siebird** [comment]
Hey, I also got to the same issue and after few minutes of research I find out that you can actually stop dependancies to load in the page. I use this code at my checkout page (where stripe intent html form code is used) to stop loading jquery from commerce-stripe plugin.

```
{% do view.registerAssetBundle("yii\\web\\JqueryAsset", 0) %}
```

I dont know if there is any other better way to do so.

**Comment by samhibberd** [comment]
Now that `getPaymentFormHtml()` is recommended for use on the front end, can the dependency be removed for the asset. Looks to be only vanilla js used in paymentform.js unless i'm missing something:

https://github.com/craftcms/commerce-stripe/blob/develop/src/web/assets/elementsform/js/paymentForm.js

The asset still looks to depend on Jquery:

https://github.com/craftcms/commerce-stripe/blob/develop/src/web/assets/elementsform/ElementsFormAsset.php
