### ISSUE TITLE
Font size of 14px on StripeElement causes iOS input zoom

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/commerce-stripe#94]
In `/vendor/craftcms/commerce-stripe/src/web/assets/intentsform/js/paymentForm.js`, the plugin is setting a font-size of 14px on the Stripe input element... but it's a fairly well-known pitfall that setting inputs to anything less than 16px causes iOS to 'zoom' the interface on focus, requiring the user to un-zoom manually after blur, or just put up with scrolling sideways.

Is there a safe way of changing this without having to duplicate the whole file and serve it myself instead of using the `getPaymentFormHtml()` tag?

**Comment by raulDeflection** [comment]
Hello, did you find the solution to this?
