### ISSUE TITLE
PHP 7.4 compatibility with Stripe 7.0.0

### ISSUE THREAD

**Issue by smcyr** [craftcms/commerce-stripe#95]
Right now, the plugin gives this error on the checkout page:
`array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead`
The library stripe-php fixed a couple of errors on version 7.0.0:
https://github.com/stripe/stripe-php/pull/725
So, the plugin should be updated for this version:
https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v7
Thanks!

**Comment by Dev2637** [comment]
I to now suffer from this error.
Craft: 3.4.8
Commerce: 3.0.10
Stripe for Craft Commerce: 2.2.3

`array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead`

Above error is displayed also in the CP when adding new subscription plan.

**Comment by sebschaefer** [comment]
Another problem when trying to open an active subscription in CP:

`Trying to access array offset on value of type int`
vendor/stripe/stripe-php/lib/Util/Util.php:45

Latest craft commerce & commerce-stripe plugin versions.

**Comment by andrelopez** [comment]
Stripe Payments v2.5.0 has added `stripe/stripe-php` requirement to ^7.0.0  (Upvote anyone who has Craft Commerce and Stripe Payments installed and need support for php 7.4)

**Comment by 23d1** [comment]
Any movement on this?

**Comment by AndrewMac** [comment]
There also seems to be a stripe/stripe-php issue with craftcms/commerce-stripe and the latest version of Solspace Freeform :-(

**Comment by chadcrowell** [comment]
+1 on AndrewMac's report above. Freeform has updated Stripe-php to v7+ and there is a composer dependency crash between Freeform and this plugin. Please update it to stripe-php v7+ so we can upgrade plugins.  The current Freeform dependency version is `"stripe/stripe-php": "^7.27.3"`

**Comment by lukeholder** [comment]
Looking into upgrading this now.

**Comment by nfourtythree** [comment]
Hi All

Have just pushed up the updated `composer.json` with the new requirement. Have been testing payments/refunds on different PHP versions and instances and everything seems to look good.

If anyone wants to install this on a local/staging environment and let us know any feedback or issues you spot. You can do using the composer requirement below.

```json
"require": {
  "craftcms/commerce-stripe": "dev-develop#8b6f130a2ed08c4bb0eb5b8b33c19dcf90c7c68a as 2.2.3",
  "...": "..."
}
```

We will look to get a release out asap, taking into account any feedback we get.

Thanks.

**Comment by chadcrowell** [comment]
I made the update to composer.json on local but my composer update command is just spinning for minutes on end with no output. 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

I can't seem to get it to fully run. I do have a lot of plugins on this site but never have seen this happen. Replacing the original `"craftcms/commerce-stripe": "2.2.3",` composer update does run.

**Comment by nfourtythree** [comment]
Hi @chadcrowell 

You will likely need to add the following lines to your `composer.json`

```
  ...
  "minimum-stability": "dev",
  "prefer-stable": true,
  ...
```

I would suggest that this is only recommended when testing locally or in a staging environment.

**Comment by chadcrowell** [comment]
No change. The only way composer doesn't stall on either update or install is putting it back to `"craftcms/commerce-stripe": "2.2.3",`

**Comment by angrybrad** [comment]
@chadcrowell try `composer clear-cache` and/or `composer self-update` and see if that helps

**Comment by chadcrowell** [comment]
Did both, with no change in result. Terminal just sits there, the fans go
nuts, nothing happens. Also tried "craftcms/commerce-stripe": "dev-develop
as 2.2.3", and that didn't help either.

**Comment by nfourtythree** [comment]
Version `2.3.0` has been released with this update.

You should be able to update as you would normally (ignoring develop branch etc).

Thanks!

**Comment by focalinteractive** [comment]
@nfourtythree Same issue with @chadcrowell 
Updating from 2.2.3 to 2.3.0 is stuck at "Perform update with composer..."

**Comment by nfourtythree** [comment]
Hey @focalinteractive 

What is your requirement for this package in your `composer.json`?

Thanks

**Comment by chadcrowell** [comment]
Getting same issue as @focalinteractive above, which is the same thing I was getting above that. Fans spinning and Composer stuck.

**Comment by nfourtythree** [comment]
Hey @focalinteractive & @chadcrowell 

Have you tried removing your `vendor` directory and `composer.lock` and then running `composer install`?

**Comment by focalinteractive** [comment]
@nfourtythree Yes, ultimately that's what I did to resolve the issue days ago. However, re-installing all dependencies takes a while so it's something that we want to avoid doing on production environments.

**Comment by antcooper** [comment]
Have run into this one too. Tried all above suggestions to clear cache and vendor folder etc.

**Comment by antcooper** [comment]
> Have run into this one too. Tried all above suggestions to clear cache and vendor folder etc.

I managed to get this to work by uninstalling Freeform, run Stripe update, and then reinstall Freeform.

Make sure you backup any Freeform submissions first as uninstalling will remove them all
